import numpy as np

imagenet_classnames = ['tench',
 'goldfish',
 'great white shark',
 'tiger shark',
 'hammerhead shark',
 'electric ray',
 'stingray',
 'rooster',
 'hen',
 'ostrich',
 'brambling',
 'goldfinch',
 'house finch',
 'junco',
 'indigo bunting',
 'american robin',
 'bulbul',
 'jay',
 'magpie',
 'chickadee',
 'american dipper',
 'kite bird of prey',
 'bald eagle',
 'vulture',
 'great grey owl',
 'fire salamander',
 'smooth newt',
 'newt',
 'spotted salamander',
 'axolotl',
 'american bullfrog',
 'tree frog',
 'tailed frog',
 'loggerhead sea turtle',
 'leatherback sea turtle',
 'mud turtle',
 'terrapin',
 'box turtle',
 'banded gecko',
 'green iguana',
 'carolina anole',
 'desert grassland whiptail lizard',
 'agama',
 'frilled necked lizard',
 'alligator lizard',
 'gila monster',
 'european green lizard',
 'chameleon',
 'komodo dragon',
 'nile crocodile',
 'american alligator',
 'triceratops',
 'worm snake',
 'ring necked snake',
 'eastern hog nosed snake',
 'smooth green snake',
 'kingsnake',
 'garter snake',
 'water snake',
 'vine snake',
 'night snake',
 'boa constrictor',
 'african rock python',
 'indian cobra',
 'green mamba',
 'sea snake',
 'saharan horned viper',
 'eastern diamondback rattlesnake',
 'sidewinder rattlesnake',
 'trilobite',
 'harvestman',
 'scorpion',
 'yellow garden spider',
 'barn spider',
 'european garden spider',
 'southern black widow',
 'tarantula',
 'wolf spider',
 'tick',
 'centipede',
 'black grouse',
 'ptarmigan',
 'ruffed grouse',
 'prairie grouse',
 'peafowl',
 'quail',
 'partridge',
 'african grey parrot',
 'macaw',
 'sulphur crested cockatoo',
 'lorikeet',
 'coucal',
 'bee eater',
 'hornbill',
 'hummingbird',
 'jacamar',
 'toucan',
 'duck',
 'red breasted merganser',
 'goose',
 'black swan',
 'tusker',
 'echidna',
 'platypus',
 'wallaby',
 'koala',
 'wombat',
 'jellyfish',
 'sea anemone',
 'brain coral',
 'flatworm',
 'nematode',
 'conch',
 'snail',
 'slug',
 'sea slug',
 'chiton',
 'chambered nautilus',
 'dungeness crab',
 'rock crab',
 'fiddler crab',
 'red king crab',
 'american lobster',
 'spiny lobster',
 'crayfish',
 'hermit crab',
 'isopod',
 'white stork',
 'black stork',
 'spoonbill',
 'flamingo',
 'little blue heron',
 'great egret',
 'bittern bird',
 'crane bird',
 'limpkin',
 'common gallinule',
 'american coot',
 'bustard',
 'ruddy turnstone',
 'dunlin',
 'common redshank',
 'dowitcher',
 'oystercatcher',
 'pelican',
 'king penguin',
 'albatross',
 'grey whale',
 'killer whale',
 'dugong',
 'sea lion',
 'chihuahua',
 'japanese chin',
 'maltese',
 'pekingese',
 'shih tzu',
 'king charles spaniel',
 'papillon',
 'toy terrier',
 'rhodesian ridgeback',
 'afghan hound',
 'basset hound',
 'beagle',
 'bloodhound',
 'bluetick coonhound',
 'black and tan coonhound',
 'treeing walker coonhound',
 'english foxhound',
 'redbone coonhound',
 'borzoi',
 'irish wolfhound',
 'italian greyhound',
 'whippet',
 'ibizan hound',
 'norwegian elkhound',
 'otterhound',
 'saluki',
 'scottish deerhound',
 'weimaraner',
 'staffordshire bull terrier',
 'american staffordshire terrier',
 'bedlington terrier',
 'border terrier',
 'kerry blue terrier',
 'irish terrier',
 'norfolk terrier',
 'norwich terrier',
 'yorkshire terrier',
 'wire fox terrier',
 'lakeland terrier',
 'sealyham terrier',
 'airedale terrier',
 'cairn terrier',
 'australian terrier',
 'dandie dinmont terrier',
 'boston terrier',
 'miniature schnauzer',
 'giant schnauzer',
 'standard schnauzer',
 'scottish terrier',
 'tibetan terrier',
 'australian silky terrier',
 'soft coated wheaten terrier',
 'west highland white terrier',
 'lhasa apso',
 'flat coated retriever',
 'curly coated retriever',
 'golden retriever',
 'labrador retriever',
 'chesapeake bay retriever',
 'german shorthaired pointer',
 'vizsla',
 'english setter',
 'irish setter',
 'gordon setter',
 'brittany dog',
 'clumber spaniel',
 'english springer spaniel',
 'welsh springer spaniel',
 'cocker spaniel',
 'sussex spaniel',
 'irish water spaniel',
 'kuvasz',
 'schipperke',
 'groenendael dog',
 'malinois',
 'briard',
 'australian kelpie',
 'komondor',
 'old english sheepdog',
 'shetland sheepdog',
 'collie',
 'border collie',
 'bouvier des flandres dog',
 'rottweiler',
 'german shepherd dog',
 'dobermann',
 'miniature pinscher',
 'greater swiss mountain dog',
 'bernese mountain dog',
 'appenzeller sennenhund',
 'entlebucher sennenhund',
 'boxer',
 'bullmastiff',
 'tibetan mastiff',
 'french bulldog',
 'great dane',
 'st  bernard',
 'husky',
 'alaskan malamute',
 'siberian husky',
 'dalmatian',
 'affenpinscher',
 'basenji',
 'pug',
 'leonberger',
 'newfoundland dog',
 'great pyrenees dog',
 'samoyed',
 'pomeranian',
 'chow chow',
 'keeshond',
 'brussels griffon',
 'pembroke welsh corgi',
 'cardigan welsh corgi',
 'toy poodle',
 'miniature poodle',
 'standard poodle',
 'mexican hairless dog xoloitzcuintli',
 'grey wolf',
 'alaskan tundra wolf',
 'red wolf or maned wolf',
 'coyote',
 'dingo',
 'dhole',
 'african wild dog',
 'hyena',
 'red fox',
 'kit fox',
 'arctic fox',
 'grey fox',
 'tabby cat',
 'tiger cat',
 'persian cat',
 'siamese cat',
 'egyptian mau',
 'cougar',
 'lynx',
 'leopard',
 'snow leopard',
 'jaguar',
 'lion',
 'tiger',
 'cheetah',
 'brown bear',
 'american black bear',
 'polar bear',
 'sloth bear',
 'mongoose',
 'meerkat',
 'tiger beetle',
 'ladybug',
 'ground beetle',
 'longhorn beetle',
 'leaf beetle',
 'dung beetle',
 'rhinoceros beetle',
 'weevil',
 'fly',
 'bee',
 'ant',
 'grasshopper',
 'cricket insect',
 'stick insect',
 'cockroach',
 'praying mantis',
 'cicada',
 'leafhopper',
 'lacewing',
 'dragonfly',
 'damselfly',
 'red admiral butterfly',
 'ringlet butterfly',
 'monarch butterfly',
 'small white butterfly',
 'sulphur butterfly',
 'gossamer winged butterfly',
 'starfish',
 'sea urchin',
 'sea cucumber',
 'cottontail rabbit',
 'hare',
 'angora rabbit',
 'hamster',
 'porcupine',
 'fox squirrel',
 'marmot',
 'beaver',
 'guinea pig',
 'common sorrel horse',
 'zebra',
 'pig',
 'wild boar',
 'warthog',
 'hippopotamus',
 'ox',
 'water buffalo',
 'bison',
 'ram adult male sheep',
 'bighorn sheep',
 'alpine ibex',
 'hartebeest',
 'impala antelope',
 'gazelle',
 'arabian camel',
 'llama',
 'weasel',
 'mink',
 'european polecat',
 'black footed ferret',
 'otter',
 'skunk',
 'badger',
 'armadillo',
 'three toed sloth',
 'orangutan',
 'gorilla',
 'chimpanzee',
 'gibbon',
 'siamang',
 'guenon',
 'patas monkey',
 'baboon',
 'macaque',
 'langur',
 'black and white colobus',
 'proboscis monkey',
 'marmoset',
 'white headed capuchin',
 'howler monkey',
 'titi monkey',
 'geoffroys spider monkey',
 'common squirrel monkey',
 'ring tailed lemur',
 'indri',
 'asian elephant',
 'african bush elephant',
 'red panda',
 'giant panda',
 'snoek fish',
 'eel',
 'silver salmon',
 'rock beauty fish',
 'clownfish',
 'sturgeon',
 'gar fish',
 'lionfish',
 'pufferfish',
 'abacus',
 'abaya',
 'academic gown',
 'accordion',
 'acoustic guitar',
 'aircraft carrier',
 'airliner',
 'airship',
 'altar',
 'ambulance',
 'amphibious vehicle',
 'analog clock',
 'apiary',
 'apron',
 'trash can',
 'assault rifle',
 'backpack',
 'bakery',
 'balance beam',
 'balloon',
 'ballpoint pen',
 'band aid',
 'banjo',
 'baluster  handrail',
 'barbell',
 'barber chair',
 'barbershop',
 'barn',
 'barometer',
 'barrel',
 'wheelbarrow',
 'baseball',
 'basketball',
 'bassinet',
 'bassoon',
 'swimming cap',
 'bath towel',
 'bathtub',
 'station wagon',
 'lighthouse',
 'beaker',
 'military hat bearskin or shako',
 'beer bottle',
 'beer glass',
 'bell tower',
 'baby bib',
 'tandem bicycle',
 'bikini',
 'ring binder',
 'binoculars',
 'birdhouse',
 'boathouse',
 'bobsleigh',
 'bolo tie',
 'poke bonnet',
 'bookcase',
 'bookstore',
 'bottle cap',
 'hunting bow',
 'bow tie',
 'brass memorial plaque',
 'bra',
 'breakwater',
 'breastplate',
 'broom',
 'bucket',
 'buckle',
 'bulletproof vest',
 'high speed train',
 'butcher shop',
 'taxicab',
 'cauldron',
 'candle',
 'cannon',
 'canoe',
 'can opener',
 'cardigan',
 'car mirror',
 'carousel',
 'tool kit',
 'cardboard box  carton',
 'car wheel',
 'automated teller machine',
 'cassette',
 'cassette player',
 'castle',
 'catamaran',
 'cd player',
 'cello',
 'mobile phone',
 'chain',
 'chain link fence',
 'chain mail',
 'chainsaw',
 'storage chest',
 'chiffonier',
 'bell or wind chime',
 'china cabinet',
 'christmas stocking',
 'church',
 'movie theater',
 'cleaver',
 'cliff dwelling',
 'cloak',
 'clogs',
 'cocktail shaker',
 'coffee mug',
 'coffeemaker',
 'spiral or coil',
 'combination lock',
 'computer keyboard',
 'candy store',
 'container ship',
 'convertible',
 'corkscrew',
 'cornet',
 'cowboy boot',
 'cowboy hat',
 'cradle',
 'construction crane',
 'crash helmet',
 'crate',
 'infant bed',
 'crock pot',
 'croquet ball',
 'crutch',
 'cuirass',
 'dam',
 'desk',
 'desktop computer',
 'rotary dial telephone',
 'diaper',
 'digital clock',
 'digital watch',
 'dining table',
 'dishcloth',
 'dishwasher',
 'disc brake',
 'dock',
 'dog sled',
 'dome',
 'doormat',
 'drilling rig',
 'drum',
 'drumstick',
 'dumbbell',
 'dutch oven',
 'electric fan',
 'electric guitar',
 'electric locomotive',
 'entertainment center',
 'envelope',
 'espresso machine',
 'face powder',
 'feather boa',
 'filing cabinet',
 'fireboat',
 'fire truck',
 'fire screen',
 'flagpole',
 'flute',
 'folding chair',
 'football helmet',
 'forklift',
 'fountain',
 'fountain pen',
 'four poster bed',
 'freight car',
 'french horn',
 'frying pan',
 'fur coat',
 'garbage truck',
 'gas mask or respirator',
 'gas pump',
 'goblet',
 'go kart',
 'golf ball',
 'golf cart',
 'gondola',
 'gong',
 'gown',
 'grand piano',
 'greenhouse',
 'radiator grille',
 'grocery store',
 'guillotine',
 'hair clip',
 'hair spray',
 'half track',
 'hammer',
 'hamper',
 'hair dryer',
 'hand held computer',
 'handkerchief',
 'hard disk drive',
 'harmonica',
 'harp',
 'combine harvester',
 'hatchet',
 'holster',
 'home theater',
 'honeycomb',
 'hook',
 'hoop skirt',
 'gymnastic horizontal bar',
 'horse drawn vehicle',
 'hourglass',
 'ipod',
 'clothes iron',
 'carved pumpkin',
 'jeans',
 'jeep',
 't shirt',
 'jigsaw puzzle',
 'rickshaw',
 'joystick',
 'kimono',
 'knee pad',
 'knot',
 'lab coat',
 'ladle',
 'lampshade',
 'laptop computer',
 'lawn mower',
 'lens cap',
 'letter opener',
 'library',
 'lifeboat',
 'lighter',
 'limousine',
 'ocean liner',
 'lipstick',
 'slip on shoe',
 'lotion',
 'music speaker',
 'loupe magnifying glass',
 'sawmill',
 'magnetic compass',
 'messenger bag',
 'mailbox',
 'tights',
 'one piece bathing suit',
 'manhole cover',
 'maraca',
 'marimba',
 'mask',
 'matchstick',
 'maypole',
 'maze',
 'measuring cup',
 'medicine cabinet',
 'megalith',
 'microphone',
 'microwave oven',
 'military uniform',
 'milk can',
 'minibus',
 'miniskirt',
 'minivan',
 'missile',
 'mitten',
 'mixing bowl',
 'mobile home',
 'ford model t',
 'modem',
 'monastery',
 'monitor',
 'moped',
 'mortar and pestle',
 'graduation cap',
 'mosque',
 'mosquito net',
 'vespa',
 'mountain bike',
 'tent',
 'computer mouse',
 'mousetrap',
 'moving van',
 'muzzle',
 'metal nail',
 'neck brace',
 'necklace',
 'baby pacifier',
 'notebook computer',
 'obelisk',
 'oboe',
 'ocarina',
 'odometer',
 'oil filter',
 'pipe organ',
 'oscilloscope',
 'overskirt',
 'bullock cart',
 'oxygen mask',
 'product packet  packaging',
 'paddle',
 'paddle wheel',
 'padlock',
 'paintbrush',
 'pajamas',
 'palace',
 'pan flute',
 'paper towel',
 'parachute',
 'parallel bars',
 'park bench',
 'parking meter',
 'railroad car',
 'patio',
 'payphone',
 'pedestal',
 'pencil case',
 'pencil sharpener',
 'perfume',
 'petri dish',
 'photocopier',
 'plectrum',
 'pickelhaube',
 'picket fence',
 'pickup truck',
 'pier',
 'piggy bank',
 'pill bottle',
 'pillow',
 'ping pong ball',
 'pinwheel',
 'pirate ship',
 'drink pitcher',
 'block plane',
 'planetarium',
 'plastic bag',
 'plate rack',
 'farm plow',
 'plunger',
 'polaroid camera',
 'pole',
 'police van',
 'poncho',
 'pool table',
 'soda bottle',
 'plant pot',
 'potters wheel',
 'power drill',
 'prayer rug',
 'printer',
 'prison',
 'missile',
 'projector',
 'hockey puck',
 'punching bag',
 'purse',
 'quill',
 'quilt',
 'race car',
 'racket',
 'radiator',
 'radio',
 'radio telescope',
 'rain barrel',
 'recreational vehicle',
 'fishing casting reel',
 'reflex camera',
 'refrigerator',
 'remote control',
 'restaurant',
 'revolver',
 'rifle',
 'rocking chair',
 'rotisserie',
 'eraser',
 'rugby ball',
 'ruler measuring stick',
 'sneaker',
 'safe',
 'safety pin',
 'salt shaker',
 'sandal',
 'sarong',
 'saxophone',
 'scabbard',
 'weighing scale',
 'school bus',
 'schooner',
 'scoreboard',
 'crt monitor',
 'screw',
 'screwdriver',
 'seat belt',
 'sewing machine',
 'shield',
 'shoe store',
 'shoji screen  room divider',
 'shopping basket',
 'shopping cart',
 'shovel',
 'shower cap',
 'shower curtain',
 'ski',
 'balaclava ski mask',
 'sleeping bag',
 'slide rule',
 'sliding door',
 'slot machine',
 'snorkel',
 'snowmobile',
 'snowplow',
 'soap dispenser',
 'soccer ball',
 'sock',
 'solar thermal collector',
 'sombrero',
 'soup bowl',
 'keyboard space bar',
 'space heater',
 'space shuttle',
 'spatula',
 'motorboat',
 'spider web',
 'spindle',
 'sports car',
 'spotlight',
 'stage',
 'steam locomotive',
 'through arch bridge',
 'steel drum',
 'stethoscope',
 'scarf',
 'stone wall',
 'stopwatch',
 'stove',
 'strainer',
 'tram',
 'stretcher',
 'couch',
 'stupa',
 'submarine',
 'suit',
 'sundial',
 'sunglasses',
 'sunglasses',
 'sunscreen',
 'suspension bridge',
 'mop',
 'sweatshirt',
 'swim trunks  shorts',
 'swing',
 'electrical switch',
 'syringe',
 'table lamp',
 'tank',
 'tape player',
 'teapot',
 'teddy bear',
 'television',
 'tennis ball',
 'thatched roof',
 'front curtain',
 'thimble',
 'threshing machine',
 'throne',
 'tile roof',
 'toaster',
 'tobacco shop',
 'toilet seat',
 'torch',
 'totem pole',
 'tow truck',
 'toy store',
 'tractor',
 'semi trailer truck',
 'tray',
 'trench coat',
 'tricycle',
 'trimaran',
 'tripod',
 'triumphal arch, arch of orange, arch of titus',
 'bus',
 'trombone',
 'hot tub',
 'turnstile',
 'typewriter keyboard',
 'umbrella',
 'unicycle',
 'upright piano',
 'vacuum cleaner',
 'vase',
 'vaulted or arched ceiling',
 'velvet fabric',
 'vending machine',
 'vestment',
 'viaduct',
 'violin',
 'volleyball',
 'waffle iron',
 'wall clock',
 'wallet',
 'wardrobe',
 'military aircraft',
 'sink',
 'washing machine',
 'water bottle',
 'water jug',
 'water tower',
 'whiskey jug',
 'whistle',
 'hair wig',
 'window screen',
 'window shade',
 'windsor tie',
 'wine bottle',
 'airplane wing',
 'wok',
 'wooden spoon',
 'wool',
 'split rail fence',
 'shipwreck',
 'sailboat',
 'yurt',
 'website',
 'comic book',
 'crossword',
 'traffic or street sign',
 'traffic light',
 'dust jacket',
 'menu',
 'plate',
 'guacamole',
 'consomme',
 'hot pot',
 'trifle',
 'ice cream',
 'popsicle',
 'baguette',
 'bagel',
 'pretzel',
 'cheeseburger',
 'hot dog',
 'mashed potatoes',
 'cabbage',
 'broccoli',
 'cauliflower',
 'zucchini',
 'spaghetti squash',
 'acorn squash',
 'butternut squash',
 'cucumber',
 'artichoke',
 'bell pepper',
 'cardoon',
 'mushroom',
 'granny smith apple',
 'strawberry',
 'orange',
 'lemon',
 'fig',
 'pineapple',
 'banana',
 'jackfruit',
 'cherimoya custard apple',
 'pomegranate',
 'hay',
 'carbonara',
 'chocolate syrup',
 'dough',
 'meatloaf',
 'pizza',
 'pot pie',
 'burrito',
 'red wine',
 'espresso',
 'tea cup',
 'eggnog',
 'mountain',
 'bubble',
 'cliff',
 'coral reef',
 'geyser',
 'lakeshore',
 'promontory',
 'sandbar',
 'beach',
 'valley',
 'volcano',
 'baseball player',
 'bridegroom',
 'scuba diver',
 'rapeseed',
 'daisy',
 'yellow ladys slipper',
 'corn',
 'acorn',
 'rose hip',
 'horse chestnut seed',
 'coral fungus',
 'agaric',
 'gyromitra',
 'stinkhorn mushroom',
 'earth star fungus',
 'hen of the woods mushroom',
 'bolete',
 'corn cob',
 'toilet paper']

def get_imagenet_classnames():
    return imagenet_classnames

imagenet_captions_classnames = ['kit fox',
 'english setter',
 'siberian husky',
 'australian terrier',
 'english springer',
 'grey whale',
 'lesser panda',
 'egyptian cat',
 'ibex',
 'persian cat',
 'cougar',
 'gazelle',
 'porcupine',
 'sea lion',
 'malamute',
 'badger',
 'great dane',
 'walker hound',
 'welsh springer spaniel',
 'whippet',
 'scottish deerhound',
 'killer whale',
 'mink',
 'african elephant',
 'weimaraner',
 'soft coated wheaten terrier',
 'dandie dinmont',
 'red wolf',
 'old english sheepdog',
 'jaguar',
 'otterhound',
 'bloodhound',
 'airedale',
 'hyena',
 'meerkat',
 'giant schnauzer',
 'titi',
 'three toed sloth',
 'sorrel',
 'black footed ferret',
 'dalmatian',
 'black and tan coonhound',
 'papillon',
 'skunk',
 'staffordshire bullterrier',
 'mexican hairless',
 'bouvier des flandres',
 'weasel',
 'miniature poodle',
 'cardigan',
 'malinois',
 'bighorn',
 'fox squirrel',
 'colobus',
 'tiger cat',
 'lhasa',
 'impala',
 'coyote',
 'yorkshire terrier',
 'newfoundland',
 'brown bear',
 'red fox',
 'norwegian elkhound',
 'rottweiler',
 'hartebeest',
 'saluki',
 'grey fox',
 'schipperke',
 'pekinese',
 'brabancon griffon',
 'west highland white terrier',
 'sealyham terrier',
 'guenon',
 'mongoose',
 'indri',
 'tiger',
 'irish wolfhound',
 'wild boar',
 'entlebucher',
 'zebra',
 'ram',
 'french bulldog',
 'orangutan',
 'basenji',
 'leopard',
 'bernese mountain dog',
 'maltese dog',
 'norfolk terrier',
 'toy terrier',
 'vizsla',
 'cairn',
 'squirrel monkey',
 'groenendael',
 'clumber',
 'siamese cat',
 'chimpanzee',
 'komondor',
 'afghan hound',
 'japanese spaniel',
 'proboscis monkey',
 'guinea pig',
 'white wolf',
 'ice bear',
 'gorilla',
 'borzoi',
 'toy poodle',
 'kerry blue terrier',
 'ox',
 'scotch terrier',
 'tibetan mastiff',
 'spider monkey',
 'doberman',
 'boston bull',
 'greater swiss mountain dog',
 'appenzeller',
 'shih tzu',
 'irish water spaniel',
 'pomeranian',
 'bedlington terrier',
 'warthog',
 'arabian camel',
 'siamang',
 'miniature schnauzer',
 'collie',
 'golden retriever',
 'irish terrier',
 'affenpinscher',
 'border collie',
 'hare',
 'boxer',
 'silky terrier',
 'beagle',
 'leonberg',
 'german short haired pointer',
 'patas',
 'dhole',
 'baboon',
 'macaque',
 'chesapeake bay retriever',
 'bull mastiff',
 'kuvasz',
 'capuchin',
 'pug',
 'curly coated retriever',
 'norwich terrier',
 'flat coated retriever',
 'hog',
 'keeshond',
 'eskimo dog',
 'brittany spaniel',
 'standard poodle',
 'lakeland terrier',
 'snow leopard',
 'gordon setter',
 'dingo',
 'standard schnauzer',
 'hamster',
 'tibetan terrier',
 'arctic fox',
 'wire haired fox terrier',
 'basset',
 'water buffalo',
 'american black bear',
 'angora',
 'bison',
 'howler monkey',
 'hippopotamus',
 'chow',
 'giant panda',
 'american staffordshire terrier',
 'shetland sheepdog',
 'great pyrenees',
 'chihuahua',
 'tabby',
 'marmoset',
 'labrador retriever',
 'saint bernard',
 'armadillo',
 'samoyed',
 'bluetick',
 'redbone',
 'polecat',
 'marmot',
 'kelpie',
 'gibbon',
 'llama',
 'miniature pinscher',
 'wood rabbit',
 'italian greyhound',
 'lion',
 'cocker spaniel',
 'irish setter',
 'dugong',
 'indian elephant',
 'beaver',
 'sussex spaniel',
 'pembroke',
 'blenheim spaniel',
 'madagascar cat',
 'rhodesian ridgeback',
 'lynx',
 'african hunting dog',
 'langur',
 'ibizan hound',
 'timber wolf',
 'cheetah',
 'english foxhound',
 'briard',
 'sloth bear',
 'border terrier',
 'german shepherd',
 'otter',
 'koala',
 'tusker',
 'echidna',
 'wallaby',
 'platypus',
 'wombat',
 'revolver',
 'umbrella',
 'schooner',
 'soccer ball',
 'accordion',
 'ant',
 'starfish',
 'chambered nautilus',
 'grand piano',
 'laptop',
 'strawberry',
 'airliner',
 'warplane',
 'airship',
 'balloon',
 'space shuttle',
 'fireboat',
 'gondola',
 'speedboat',
 'lifeboat',
 'canoe',
 'yawl',
 'catamaran',
 'trimaran',
 'container ship',
 'liner',
 'pirate',
 'aircraft carrier',
 'submarine',
 'wreck',
 'half track',
 'tank',
 'missile',
 'bobsled',
 'dogsled',
 'bicycle built for two',
 'mountain bike',
 'freight car',
 'passenger car',
 'barrow',
 'shopping cart',
 'motor scooter',
 'forklift',
 'electric locomotive',
 'steam locomotive',
 'amphibian',
 'ambulance',
 'beach wagon',
 'cab',
 'convertible',
 'jeep',
 'limousine',
 'minivan',
 'model t',
 'racer',
 'sports car',
 'go kart',
 'golfcart',
 'moped',
 'snowplow',
 'fire engine',
 'garbage truck',
 'pickup',
 'tow truck',
 'trailer truck',
 'moving van',
 'police van',
 'recreational vehicle',
 'streetcar',
 'snowmobile',
 'tractor',
 'mobile home',
 'tricycle',
 'unicycle',
 'horse cart',
 'jinrikisha',
 'oxcart',
 'bassinet',
 'cradle',
 'crib',
 'four poster',
 'bookcase',
 'china cabinet',
 'medicine chest',
 'chiffonier',
 'table lamp',
 'file',
 'park bench',
 'barber chair',
 'throne',
 'folding chair',
 'rocking chair',
 'studio couch',
 'toilet seat',
 'desk',
 'pool table',
 'dining table',
 'entertainment center',
 'wardrobe',
 'granny smith',
 'orange',
 'lemon',
 'fig',
 'pineapple',
 'banana',
 'jackfruit',
 'custard apple',
 'pomegranate',
 'acorn',
 'hip',
 'ear',
 'rapeseed',
 'corn',
 'buckeye',
 'organ',
 'upright',
 'chime',
 'drum',
 'gong',
 'maraca',
 'marimba',
 'steel drum',
 'banjo',
 'cello',
 'violin',
 'harp',
 'acoustic guitar',
 'electric guitar',
 'cornet',
 'french horn',
 'trombone',
 'harmonica',
 'ocarina',
 'panpipe',
 'bassoon',
 'oboe',
 'sax',
 'flute',
 'daisy',
 "yellow lady's slipper",
 'cliff',
 'valley',
 'alp',
 'volcano',
 'promontory',
 'sandbar',
 'coral reef',
 'lakeside',
 'seashore',
 'geyser',
 'hatchet',
 'cleaver',
 'letter opener',
 'plane',
 'power drill',
 'lawn mower',
 'hammer',
 'corkscrew',
 'can opener',
 'plunger',
 'screwdriver',
 'shovel',
 'plow',
 'chain saw',
 'cock',
 'hen',
 'ostrich',
 'brambling',
 'goldfinch',
 'house finch',
 'junco',
 'indigo bunting',
 'robin',
 'bulbul',
 'jay',
 'magpie',
 'chickadee',
 'water ouzel',
 'kite',
 'bald eagle',
 'vulture',
 'great grey owl',
 'black grouse',
 'ptarmigan',
 'ruffed grouse',
 'prairie chicken',
 'peacock',
 'quail',
 'partridge',
 'african grey',
 'macaw',
 'sulphur crested cockatoo',
 'lorikeet',
 'coucal',
 'bee eater',
 'hornbill',
 'hummingbird',
 'jacamar',
 'toucan',
 'drake',
 'red breasted merganser',
 'goose',
 'black swan',
 'white stork',
 'black stork',
 'spoonbill',
 'flamingo',
 'american egret',
 'little blue heron',
 'bittern',
 'crane',
 'limpkin',
 'american coot',
 'bustard',
 'ruddy turnstone',
 'red backed sandpiper',
 'redshank',
 'dowitcher',
 'oystercatcher',
 'european gallinule',
 'pelican',
 'king penguin',
 'albatross',
 'great white shark',
 'tiger shark',
 'hammerhead',
 'electric ray',
 'stingray',
 'barracouta',
 'coho',
 'tench',
 'goldfish',
 'eel',
 'rock beauty',
 'anemone fish',
 'lionfish',
 'puffer',
 'sturgeon',
 'gar',
 'loggerhead',
 'leatherback turtle',
 'mud turtle',
 'terrapin',
 'box turtle',
 'banded gecko',
 'common iguana',
 'american chameleon',
 'whiptail',
 'agama',
 'frilled lizard',
 'alligator lizard',
 'gila monster',
 'green lizard',
 'african chameleon',
 'komodo dragon',
 'triceratops',
 'african crocodile',
 'american alligator',
 'thunder snake',
 'ringneck snake',
 'hognose snake',
 'green snake',
 'king snake',
 'garter snake',
 'water snake',
 'vine snake',
 'night snake',
 'boa constrictor',
 'rock python',
 'indian cobra',
 'green mamba',
 'sea snake',
 'horned viper',
 'diamondback',
 'sidewinder',
 'european fire salamander',
 'common newt',
 'eft',
 'spotted salamander',
 'axolotl',
 'bullfrog',
 'tree frog',
 'tailed frog',
 'whistle',
 'wing',
 'paintbrush',
 'hand blower',
 'oxygen mask',
 'snorkel',
 'loudspeaker',
 'microphone',
 'screen',
 'mouse',
 'electric fan',
 'oil filter',
 'strainer',
 'space heater',
 'stove',
 'guillotine',
 'barometer',
 'rule',
 'odometer',
 'scale',
 'analog clock',
 'digital clock',
 'wall clock',
 'hourglass',
 'sundial',
 'parking meter',
 'stopwatch',
 'digital watch',
 'stethoscope',
 'syringe',
 'magnetic compass',
 'binoculars',
 'projector',
 'sunglasses',
 'loupe',
 'radio telescope',
 'bow',
 'cannon',
 'assault rifle',
 'rifle',
 'projectile',
 'computer keyboard',
 'typewriter keyboard',
 'crane',
 'lighter',
 'abacus',
 'cash machine',
 'slide rule',
 'desktop computer',
 'hand held computer',
 'notebook',
 'web site',
 'harvester',
 'thresher',
 'printer',
 'slot',
 'vending machine',
 'sewing machine',
 'joystick',
 'switch',
 'hook',
 'car wheel',
 'paddlewheel',
 'pinwheel',
 "potter's wheel",
 'gas pump',
 'carousel',
 'swing',
 'reel',
 'radiator',
 'puck',
 'hard disc',
 'sunglass',
 'pick',
 'car mirror',
 'solar dish',
 'remote control',
 'disk brake',
 'buckle',
 'hair slide',
 'knot',
 'combination lock',
 'padlock',
 'nail',
 'safety pin',
 'screw',
 'muzzle',
 'seat belt',
 'ski',
 'candle',
 "jack o' lantern",
 'spotlight',
 'torch',
 'neck brace',
 'pier',
 'tripod',
 'maypole',
 'mousetrap',
 'spider web',
 'trilobite',
 'harvestman',
 'scorpion',
 'black and gold garden spider',
 'barn spider',
 'garden spider',
 'black widow',
 'tarantula',
 'wolf spider',
 'tick',
 'centipede',
 'isopod',
 'dungeness crab',
 'rock crab',
 'fiddler crab',
 'king crab',
 'american lobster',
 'spiny lobster',
 'crayfish',
 'hermit crab',
 'tiger beetle',
 'ladybug',
 'ground beetle',
 'long horned beetle',
 'leaf beetle',
 'dung beetle',
 'rhinoceros beetle',
 'weevil',
 'fly',
 'bee',
 'grasshopper',
 'cricket',
 'walking stick',
 'cockroach',
 'mantis',
 'cicada',
 'leafhopper',
 'lacewing',
 'dragonfly',
 'damselfly',
 'admiral',
 'ringlet',
 'monarch',
 'cabbage butterfly',
 'sulphur butterfly',
 'lycaenid',
 'jellyfish',
 'sea anemone',
 'brain coral',
 'flatworm',
 'nematode',
 'conch',
 'snail',
 'slug',
 'sea slug',
 'chiton',
 'sea urchin',
 'sea cucumber',
 'iron',
 'espresso maker',
 'microwave',
 'dutch oven',
 'rotisserie',
 'toaster',
 'waffle iron',
 'vacuum',
 'dishwasher',
 'refrigerator',
 'washer',
 'crock pot',
 'frying pan',
 'wok',
 'caldron',
 'coffeepot',
 'teapot',
 'spatula',
 'altar',
 'triumphal arch',
 'patio',
 'steel arch bridge',
 'suspension bridge',
 'viaduct',
 'barn',
 'greenhouse',
 'palace',
 'monastery',
 'library',
 'apiary',
 'boathouse',
 'church',
 'mosque',
 'stupa',
 'planetarium',
 'restaurant',
 'cinema',
 'home theater',
 'lumbermill',
 'coil',
 'obelisk',
 'totem pole',
 'castle',
 'prison',
 'grocery store',
 'bakery',
 'barbershop',
 'bookshop',
 'butcher shop',
 'confectionery',
 'shoe shop',
 'tobacco shop',
 'toyshop',
 'fountain',
 'cliff dwelling',
 'yurt',
 'dock',
 'brass',
 'megalith',
 'bannister',
 'breakwater',
 'dam',
 'chainlink fence',
 'picket fence',
 'worm fence',
 'stone wall',
 'grille',
 'sliding door',
 'turnstile',
 'mountain tent',
 'scoreboard',
 'honeycomb',
 'plate rack',
 'pedestal',
 'beacon',
 'mashed potato',
 'bell pepper',
 'head cabbage',
 'broccoli',
 'cauliflower',
 'zucchini',
 'spaghetti squash',
 'acorn squash',
 'butternut squash',
 'cucumber',
 'artichoke',
 'cardoon',
 'mushroom',
 'shower curtain',
 'jean',
 'carton',
 'handkerchief',
 'sandal',
 'ashcan',
 'safe',
 'plate',
 'necklace',
 'croquet ball',
 'fur coat',
 'thimble',
 'pajama',
 'running shoe',
 'cocktail shaker',
 'chest',
 'manhole cover',
 'modem',
 'tub',
 'tray',
 'balance beam',
 'bagel',
 'prayer rug',
 'kimono',
 'hot pot',
 'whiskey jug',
 'knee pad',
 'book jacket',
 'spindle',
 'ski mask',
 'beer bottle',
 'crash helmet',
 'bottlecap',
 'tile roof',
 'mask',
 'maillot',
 'petri dish',
 'football helmet',
 'bathing cap',
 'teddy',
 'holster',
 'pop bottle',
 'photocopier',
 'vestment',
 'crossword puzzle',
 'golf ball',
 'trifle',
 'suit',
 'water tower',
 'feather boa',
 'cloak',
 'red wine',
 'drumstick',
 'shield',
 'christmas stocking',
 'hoopskirt',
 'menu',
 'stage',
 'bonnet',
 'meat loaf',
 'baseball',
 'face powder',
 'scabbard',
 'sunscreen',
 'beer glass',
 'hen of the woods',
 'guacamole',
 'lampshade',
 'wool',
 'hay',
 'bow tie',
 'mailbag',
 'water jug',
 'bucket',
 'dishrag',
 'soup bowl',
 'eggnog',
 'mortar',
 'trench coat',
 'paddle',
 'chain',
 'swab',
 'mixing bowl',
 'potpie',
 'wine bottle',
 'shoji',
 'bulletproof vest',
 'drilling platform',
 'binder',
 'cardigan',
 'sweatshirt',
 'pot',
 'birdhouse',
 'hamper',
 'ping pong ball',
 'pencil box',
 'pay phone',
 'consomme',
 'apron',
 'punching bag',
 'backpack',
 'groom',
 'bearskin',
 'pencil sharpener',
 'broom',
 'mosquito net',
 'abaya',
 'mortarboard',
 'poncho',
 'crutch',
 'polaroid camera',
 'space bar',
 'cup',
 'racket',
 'traffic light',
 'quill',
 'radio',
 'dough',
 'cuirass',
 'military uniform',
 'lipstick',
 'shower cap',
 'monitor',
 'oscilloscope',
 'mitten',
 'brassiere',
 'french loaf',
 'vase',
 'milk can',
 'rugby ball',
 'paper towel',
 'earthstar',
 'envelope',
 'miniskirt',
 'cowboy hat',
 'trolleybus',
 'perfume',
 'bathtub',
 'hotdog',
 'coral fungus',
 'bullet train',
 'pillow',
 'toilet tissue',
 'cassette',
 "carpenter's kit",
 'ladle',
 'stinkhorn',
 'lotion',
 'hair spray',
 'academic gown',
 'dome',
 'crate',
 'wig',
 'burrito',
 'pill bottle',
 'chain mail',
 'theater curtain',
 'window shade',
 'barrel',
 'washbasin',
 'ballpoint',
 'basketball',
 'bath towel',
 'cowboy boot',
 'gown',
 'window screen',
 'agaric',
 'cellular telephone',
 'nipple',
 'barbell',
 'mailbox',
 'lab coat',
 'fire screen',
 'minibus',
 'packet',
 'maze',
 'pole',
 'horizontal bar',
 'sombrero',
 'pickelhaube',
 'rain barrel',
 'wallet',
 'cassette player',
 'comic book',
 'piggy bank',
 'street sign',
 'bell cote',
 'fountain pen',
 'windsor tie',
 'volleyball',
 'overskirt',
 'sarong',
 'purse',
 'bolo tie',
 'bib',
 'parachute',
 'sleeping bag',
 'television',
 'swimming trunks',
 'measuring cup',
 'espresso',
 'pizza',
 'breastplate',
 'shopping basket',
 'wooden spoon',
 'saltshaker',
 'chocolate sauce',
 'ballplayer',
 'goblet',
 'gyromitra',
 'stretcher',
 'water bottle',
 'dial telephone',
 'soap dispenser',
 'jersey',
 'school bus',
 'jigsaw puzzle',
 'plastic bag',
 'reflex camera',
 'diaper',
 'band aid',
 'ice lolly',
 'velvet',
 'tennis ball',
 'gasmask',
 'doormat',
 'loafer',
 'ice cream',
 'pretzel',
 'quilt',
 'maillot',
 'tape player',
 'clog',
 'ipod',
 'bolete',
 'scuba diver',
 'pitcher',
 'matchstick',
 'bikini',
 'sock',
 'cd player',
 'lens cap',
 'thatch',
 'vault',
 'beaker',
 'bubble',
 'cheeseburger',
 'parallel bars',
 'flagpole',
 'coffee mug',
 'rubber eraser',
 'stole',
 'carbonara',
 'dumbbell']

def get_imagenet_captions_classnames():
    return imagenet_captions_classnames

ir_idx = [1, 2, 4, 6, 8, 9, 11, 13, 22, 23, 26, 29, 31, 39, 47, 63, 71, 76, 79, 84, 90, 94, 96, 97, 99, 100, 105, 107, 113, 122, 
125, 130, 132, 144, 145, 147, 148, 150, 151, 155, 160, 161, 162, 163, 171, 172, 178, 187, 195, 199, 203, 207, 208, 219, 
231, 232, 234, 235, 242, 245, 247, 250, 251, 254, 259, 260, 263, 265, 267, 269, 276, 277, 281, 288, 289, 291, 292, 293, 
296, 299, 301, 308, 309, 310, 311, 314, 315, 319, 323, 327, 330, 334, 335, 337, 338, 340, 341, 344, 347, 353, 355, 361, 
362, 365, 366, 367, 368, 372, 388, 390, 393, 397, 401, 407, 413, 414, 425, 428, 430, 435, 437, 441, 447, 448, 457, 462, 
463, 469, 470, 471, 472, 476, 483, 487, 515, 546, 555, 558, 570, 579, 583, 587, 593, 594, 596, 609, 613, 617, 621, 629, 
637, 657, 658, 701, 717, 724, 763, 768, 774, 776, 779, 780, 787, 805, 812, 815, 820, 824, 833, 847, 852, 866, 875, 883, 
889, 895, 907, 928, 931, 932, 933, 934, 936, 937, 943, 945, 947, 948, 949, 951, 953, 954, 957, 963, 965, 967, 980, 981, 
983, 988]

def get_ir_idx():
    return np.array(ir_idx)

ia_idx = [6, 11, 13, 15, 17, 22, 23, 27, 30, 37, 39, 42, 47, 50, 57, 70, 71, 76, 79, 89, 90, 94, 96, 97, 99, 105, 107, 108, 110, 
113, 124, 125, 130, 132, 143, 144, 150, 151, 207, 234, 235, 254, 277, 283, 287, 291, 295, 298, 301, 306, 307, 308, 309, 
310, 311, 313, 314, 315, 317, 319, 323, 324, 326, 327, 330, 334, 335, 336, 347, 361, 363, 372, 378, 386, 397, 400, 401, 
402, 404, 407, 411, 416, 417, 420, 425, 428, 430, 437, 438, 445, 456, 457, 461, 462, 470, 472, 483, 486, 488, 492, 496, 
514, 516, 528, 530, 539, 542, 543, 549, 552, 557, 561, 562, 569, 572, 573, 575, 579, 589, 606, 607, 609, 614, 626, 627, 
640, 641, 642, 643, 658, 668, 677, 682, 684, 687, 701, 704, 719, 736, 746, 749, 752, 758, 763, 765, 768, 773, 774, 776, 
779, 780, 786, 792, 797, 802, 803, 804, 813, 815, 820, 823, 831, 833, 835, 839, 845, 847, 850, 859, 862, 870, 879, 880, 
888, 890, 897, 900, 907, 913, 924, 932, 933, 934, 937, 943, 945, 947, 951, 954, 956, 957, 959, 971, 972, 980, 981, 984, 
986, 987, 988]

def get_ia_idx_zeroindexed():
    return np.arange(0, 200, dtype=int)

def get_ir_idx_zeroindexed():
    return np.arange(0, 200, dtype=int)

def get_ia_idx():
    return np.array(ia_idx)

icap_idx = [386, 928, 931, 704, 907, 291, 454, 76, 952, 788, 245, 937, 924, 8, 983, 816, 920, 379, 204, 396, 929, 619, 815, 88, 84, 217, 118, 935, 987, 642, 950, 951, 954, 557, 18, 967, 945, 6, 440, 348, 22, 571, 23, 963, 104, 958, 579, 312, 534, 620, 115, 298, 284, 552, 373, 997, 182, 422, 308, 839, 13, 489, 805, 832, 85, 695, 2, 863, 310, 565, 886, 455, 988, 347, 580, 425, 99, 424, 105, 107, 343, 658, 721, 443, 421, 679, 19, 825, 130, 309, 849, 879, 496, 971, 922, 985, 286, 625, 637, 943]
common_ia = [n for n in ia_idx if n in icap_idx]
common_ir = [n for n in ir_idx if n in icap_idx]

def get_icap_idx():
    return np.array(icap_idx)

def get_common_ia_idx():
    return np.array(common_ia)

def get_common_ir_idx():
    return np.array(common_ir)

def get_common_ia_idx_zeroindexed():
    return np.array([ia_idx.index(k) for k in common_ia])

def get_common_ir_idx_zeroindexed():
    return np.array([ir_idx.index(k) for k in common_ir])

def get_imagenet_r_classnames():
    imagenet_classnames_arr = np.array(imagenet_classnames)

    return imagenet_classnames_arr[ir_idx].tolist()

def get_imagenet_a_classnames():

    imagenet_classnames_arr = np.array(imagenet_classnames)

    return imagenet_classnames_arr[ia_idx].tolist()

def get_imagenet_cap_classnames():
    imagenet_classnames_arr = np.array(imagenet_classnames)

    return imagenet_classnames_arr[icap_idx].tolist()

def get_imagenet_common_ia_classnames():
    imagenet_classnames_arr = np.array(imagenet_classnames)
    return imagenet_classnames_arr[common_ia].tolist()    

def get_imagenet_common_ir_classnames():
    imagenet_classnames_arr = np.array(imagenet_classnames)
    return imagenet_classnames_arr[common_ir].tolist() 

openai_imagenet_template = [
    lambda c: f'a bad photo of a {c}.',
    lambda c: f'a photo of many {c}.',
    lambda c: f'a sculpture of a {c}.',
    lambda c: f'a photo of the hard to see {c}.',
    lambda c: f'a low resolution photo of the {c}.',
    lambda c: f'a rendering of a {c}.',
    lambda c: f'graffiti of a {c}.',
    lambda c: f'a bad photo of the {c}.',
    lambda c: f'a cropped photo of the {c}.',
    lambda c: f'a tattoo of a {c}.',
    lambda c: f'the embroidered {c}.',
    lambda c: f'a photo of a hard to see {c}.',
    lambda c: f'a bright photo of a {c}.',
    lambda c: f'a photo of a clean {c}.',
    lambda c: f'a photo of a dirty {c}.',
    lambda c: f'a dark photo of the {c}.',
    lambda c: f'a drawing of a {c}.',
    lambda c: f'a photo of my {c}.',
    lambda c: f'the plastic {c}.',
    lambda c: f'a photo of the cool {c}.',
    lambda c: f'a close-up photo of a {c}.',
    lambda c: f'a black and white photo of the {c}.',
    lambda c: f'a painting of the {c}.',
    lambda c: f'a painting of a {c}.',
    lambda c: f'a pixelated photo of the {c}.',
    lambda c: f'a sculpture of the {c}.',
    lambda c: f'a bright photo of the {c}.',
    lambda c: f'a cropped photo of a {c}.',
    lambda c: f'a plastic {c}.',
    lambda c: f'a photo of the dirty {c}.',
    lambda c: f'a jpeg corrupted photo of a {c}.',
    lambda c: f'a blurry photo of the {c}.',
    lambda c: f'a photo of the {c}.',
    lambda c: f'a good photo of the {c}.',
    lambda c: f'a rendering of the {c}.',
    lambda c: f'a {c} in a video game.',
    lambda c: f'a photo of one {c}.',
    lambda c: f'a doodle of a {c}.',
    lambda c: f'a close-up photo of the {c}.',
    lambda c: f'a photo of a {c}.',
    lambda c: f'the origami {c}.',
    lambda c: f'the {c} in a video game.',
    lambda c: f'a sketch of a {c}.',
    lambda c: f'a doodle of the {c}.',
    lambda c: f'a origami {c}.',
    lambda c: f'a low resolution photo of a {c}.',
    lambda c: f'the toy {c}.',
    lambda c: f'a rendition of the {c}.',
    lambda c: f'a photo of the clean {c}.',
    lambda c: f'a photo of a large {c}.',
    lambda c: f'a rendition of a {c}.',
    lambda c: f'a photo of a nice {c}.',
    lambda c: f'a photo of a weird {c}.',
    lambda c: f'a blurry photo of a {c}.',
    lambda c: f'a cartoon {c}.',
    lambda c: f'art of a {c}.',
    lambda c: f'a sketch of the {c}.',
    lambda c: f'a embroidered {c}.',
    lambda c: f'a pixelated photo of a {c}.',
    lambda c: f'itap of the {c}.',
    lambda c: f'a jpeg corrupted photo of the {c}.',
    lambda c: f'a good photo of a {c}.',
    lambda c: f'a plushie {c}.',
    lambda c: f'a photo of the nice {c}.',
    lambda c: f'a photo of the small {c}.',
    lambda c: f'a photo of the weird {c}.',
    lambda c: f'the cartoon {c}.',
    lambda c: f'art of the {c}.',
    lambda c: f'a drawing of the {c}.',
    lambda c: f'a photo of the large {c}.',
    lambda c: f'a black and white photo of a {c}.',
    lambda c: f'the plushie {c}.',
    lambda c: f'a dark photo of a {c}.',
    lambda c: f'itap of a {c}.',
    lambda c: f'graffiti of the {c}.',
    lambda c: f'a toy {c}.',
    lambda c: f'itap of my {c}.',
    lambda c: f'a photo of a cool {c}.',
    lambda c: f'a photo of a small {c}.',
    lambda c: f'a tattoo of the {c}.',
]

def get_openai_imagenet_template():
    return openai_imagenet_template

imagenet_cipher = ['%)@&#($^%&',
 '$&$(%*%^#&@*$)%&',
 '$&#)@&@^%) $+%&@*%)@& $)%&@^#)$*',
 '%)@*$&@&#) $)%&@^#)$*',
 '%&@^@(@(@&#)%&@&@^%^ $)%&@^#)$*',
 '@&%*@&$^%)#)@*$^ #)@^@=',
 '$)%)@*#($&#)@^@=',
 '#)$($($)%)@&#)',
 '%&@&#(',
 '$($)%)#)@*$^%&',
 '#^#)@^@(#^%*@*#($&',
 '$&$(%*%^#&@*#($^%&',
 '%&$(@+$)@& #&@*#($^%&',
 '#*@+#($^$(',
 '@*#(%^@*$&$( #^@+#(%)@*#($&',
 '@^@(@&#)@*$^@^#( #)$(#^@*#(',
 '#^@+%*#^@+%*',
 '#*@^@=',
 '@(@^$&%(@*@&',
 '$^%&@*$^$*@^%^@&@&',
 '@^@(@&#)@*$^@^#( %^@*%(%(@&#)',
 '$*@*%)@& #^@*#)%^ $(#& %(#)@&@=',
 '#^@^%*%^ @&@^$&%*@&',
 '#+@+%*%)@+#)@&',
 '$&#)@&@^%) $&#)@&@= $($+%*',
 '#&@*#)@& $)@^%*@^@(@^#(%^@&#)',
 '$)@($($(%)%& #(@&$+%)',
 '#(@&$+%)',
 '$)%($(%)%)@&%^ $)@^%*@^@(@^#(%^@&#)',
 '@^%+$(%*$(%)%*',
 '@^@(@&#)@*$^@^#( #^@+%*%*#&#)$($&',
 '%)#)@&@& #&#)$($&',
 '%)@^@*%*@&%^ #&#)$($&',
 '%*$($&$&@&#)%&@&@^%^ $)@&@^ %)@+#)%)%*@&',
 '%*@&@^%)%&@&#)#^@^$^$* $)@&@^ %)@+#)%)%*@&',
 '@(@+%^ %)@+#)%)%*@&',
 '%)@&#)#)@^%(@*#(',
 '#^$(%+ %)@+#)%)%*@&',
 '#^@^#(%^@&%^ $&@&$^$*$(',
 '$&#)@&@&#( @*$&@+@^#(@^',
 '$^@^#)$(%*@*#(@^ @^#($(%*@&',
 '%^@&$)@&#)%) $&#)@^$)$)%*@^#(%^ $+%&@*%(%)@^@*%* %*@*#=@^#)%^',
 '@^$&@^@(@^',
 '#&#)@*%*%*@&%^ #(@&$^$*@&%^ %*@*#=@^#)%^',
 '@^%*%*@*$&@^%)$(#) %*@*#=@^#)%^',
 '$&@*%*@^ @($(#($)%)@&#)',
 '@&@+#)$(%(@&@^#( $&#)@&@&#( %*@*#=@^#)%^',
 '$^%&@^@(@&%*@&$(#(',
 '$*$(@($(%^$( %^#)@^$&$(#(',
 '#(@*%*@& $^#)$($^$(%^@*%*@&',
 '@^@(@&#)@*$^@^#( @^%*%*@*$&@^%)$(#)',
 '%)#)@*$^@&#)@^%)$(%($)',
 '$+$(#)@( $)#(@^$*@&',
 '#)@*#($& #(@&$^$*@&%^ $)#(@^$*@&',
 '@&@^$)%)@&#)#( %&$($& #($($)@&%^ $)#(@^$*@&',
 '$)@($($(%)%& $&#)@&@&#( $)#(@^$*@&',
 '$*@*#($&$)#(@^$*@&',
 '$&@^#)%)@&#) $)#(@^$*@&',
 '$+@^%)@&#) $)#(@^$*@&',
 '#+@*#(@& $)#(@^$*@&',
 '#(@*$&%&%) $)#(@^$*@&',
 '#^$(@^ $^$(#($)%)#)@*$^%)$(#)',
 '@^#&#)@*$^@^#( #)$($^$* %(@=%)%&$(#(',
 '@*#(%^@*@^#( $^$(#^#)@^',
 '$&#)@&@&#( @(@^@(#^@^',
 '$)@&@^ $)#(@^$*@&',
 '$)@^%&@^#)@^#( %&$(#)#(@&%^ #+@*%(@&#)',
 '@&@^$)%)@&#)#( %^@*@^@($(#(%^#^@^$^$* #)@^%)%)%*@&$)#(@^$*@&',
 '$)@*%^@&$+@*#(%^@&#) #)@^%)%)%*@&$)#(@^$*@&',
 '%)#)@*%*$(#^@*%)@&',
 '%&@^#)#+@&$)%)@(@^#(',
 '$)$^$(#)%(@*$(#(',
 '@=@&%*%*$($+ $&@^#)%^@&#( $)%(@*%^@&#)',
 '#^@^#)#( $)%(@*%^@&#)',
 '@&@+#)$(%(@&@^#( $&@^#)%^@&#( $)%(@*%^@&#)',
 '$)$(@+%)%&@&#)#( #^%*@^$^$* $+@*%^$($+',
 '%)@^#)@^#(%)@+%*@^',
 '$+$(%*#& $)%(@*%^@&#)',
 '%)@*$^$*',
 '$^@&#(%)@*%(@&%^@&',
 '#^%*@^$^$* $&#)$(@+$)@&',
 '%(%)@^#)@(@*$&@^#(',
 '#)@+#&#&@&%^ $&#)$(@+$)@&',
 '%(#)@^@*#)@*@& $&#)$(@+$)@&',
 '%(@&@^#&$($+%*',
 '@)@+@^@*%*',
 '%(@^#)%)#)@*%^$&@&',
 '@^#&#)@*$^@^#( $&#)@&@= %(@^#)#)$(%)',
 '@(@^$^@^$+',
 '$)@+%*%(%&@+#) $^#)@&$)%)@&%^ $^$($^$*@^%)$($(',
 '%*$(#)@*$*@&@&%)',
 '$^$(@+$^@^%*',
 '#^@&@& @&@^%)@&#)',
 '%&$(#)#(#^@*%*%*',
 '%&@+@(@(@*#($&#^@*#)%^',
 '#*@^$^@^@(@^#)',
 '%)$(@+$^@^#(',
 '%^@+$^$*',
 '#)@&%^ #^#)@&@^$)%)@&%^ @(@&#)$&@^#($)@&#)',
 '$&$($($)@&',
 '#^%*@^$^$* $)$+@^#(',
 '%)@+$)$*@&#)',
 '@&$^%&@*%^#(@^',
 '%(%*@^%)@=%(@+$)',
 '$+@^%*%*@^#^@=',
 '$*$(@^%*@^',
 '$+$(@(#^@^%)',
 '#*@&%*%*@=#&@*$)%&',
 '$)@&@^ @^#(@&@($(#(@&',
 '#^#)@^@*#( $^$(#)@^%*',
 '#&%*@^%)$+$(#)@(',
 '#(@&@(@^%)$(%^@&',
 '$^$(#($^%&',
 '$)#(@^@*%*',
 '$)%*@+$&',
 '$)@&@^ $)%*@+$&',
 '$^%&@*%)$(#(',
 '$^%&@^@(#^@&#)@&%^ #(@^@+%)@*%*@+$)',
 '%^@+#($&@&#(@&$)$) $^#)@^#^',
 '#)$($^$* $^#)@^#^',
 '#&@*%^%^%*@&#) $^#)@^#^',
 '#)@&%^ $*@*#($& $^#)@^#^',
 '@^@(@&#)@*$^@^#( %*$(#^$)%)@&#)',
 '$)%(@*#(@= %*$(#^$)%)@&#)',
 '$^#)@^@=#&@*$)%&',
 '%&@&#)@(@*%) $^#)@^#^',
 '@*$)$(%($(%^',
 '$+%&@*%)@& $)%)$(#)$*',
 '#^%*@^$^$* $)%)$(#)$*',
 '$)%($($(#(#^@*%*%*',
 '#&%*@^@(@*#($&$(',
 '%*@*%)%)%*@& #^%*@+@& %&@&#)$(#(',
 '$&#)@&@^%) @&$&#)@&%)',
 '#^@*%)%)@&#)#( #^@*#)%^',
 '$^#)@^#(@& #^@*#)%^',
 '%*@*@(%($*@*#(',
 '$^$(@(@($(#( $&@^%*%*@*#(@+%*@&',
 '@^@(@&#)@*$^@^#( $^$($(%)',
 '#^@+$)%)@^#)%^',
 '#)@+%^%^@= %)@+#)#($)%)$(#(@&',
 '%^@+#(%*@*#(',
 '$^$(@(@($(#( #)@&%^$)%&@^#($*',
 '%^$($+@*%)$^%&@&#)',
 '$(@=$)%)@&#)$^@^%)$^%&@&#)',
 '%(@&%*@*$^@^#(',
 '$*@*#($& %(@&#($&@+@*#(',
 '@^%*#^@^%)#)$($)$)',
 '$&#)@&@= $+%&@^%*@&',
 '$*@*%*%*@&#) $+%&@^%*@&',
 '%^@+$&$(#($&',
 '$)@&@^ %*@*$(#(',
 '$^%&@*%&@+@^%&@+@^',
 '#*@^%(@^#(@&$)@& $^%&@*#(',
 '@(@^%*%)@&$)@&',
 '%(@&$*@*#($&@&$)@&',
 '$)%&@*%& %)#=@+',
 '$*@*#($& $^%&@^#)%*@&$) $)%(@^#(@*@&%*',
 '%(@^%(@*%*%*$(#(',
 '%)$(@= %)@&#)#)@*@&#)',
 '#)%&$(%^@&$)@*@^#( #)@*%^$&@&#^@^$^$*',
 '@^#&$&%&@^#( %&$(@+#(%^',
 '#^@^$)$)@&%) %&$(@+#(%^',
 '#^@&@^$&%*@&',
 '#^%*$($(%^%&$(@+#(%^',
 '#^%*@+@&%)@*$^$* $^$($(#(%&$(@+#(%^',
 '#^%*@^$^$* @^#(%^ %)@^#( $^$($(#(%&$(@+#(%^',
 '%)#)@&@&@*#($& $+@^%*$*@&#) $^$($(#(%&$(@+#(%^',
 '@&#($&%*@*$)%& #&$(%+%&$(@+#(%^',
 '#)@&%^#^$(#(@& $^$($(#(%&$(@+#(%^',
 '#^$(#)#=$(@*',
 '@*#)@*$)%& $+$(%*#&%&$(@+#(%^',
 '@*%)@^%*@*@^#( $&#)@&@=%&$(@+#(%^',
 '$+%&@*%(%(@&%)',
 '@*#^@*#=@^#( %&$(@+#(%^',
 '#($(#)$+@&$&@*@^#( @&%*$*%&$(@+#(%^',
 '$(%)%)@&#)%&$(@+#(%^',
 '$)@^%*@+$*@*',
 '$)$^$(%)%)@*$)%& %^@&@&#)%&$(@+#(%^',
 '$+@&@*@(@^#)@^#(@&#)',
 '$)%)@^#&#&$(#)%^$)%&@*#)@& #^@+%*%* %)@&#)#)@*@&#)',
 '@^@(@&#)@*$^@^#( $)%)@^#&#&$(#)%^$)%&@*#)@& %)@&#)#)@*@&#)',
 '#^@&%^%*@*#($&%)$(#( %)@&#)#)@*@&#)',
 '#^$(#)%^@&#) %)@&#)#)@*@&#)',
 '$*@&#)#)@= #^%*@+@& %)@&#)#)@*@&#)',
 '@*#)@*$)%& %)@&#)#)@*@&#)',
 '#($(#)#&$(%*$* %)@&#)#)@*@&#)',
 '#($(#)$+@*$^%& %)@&#)#)@*@&#)',
 '@=$(#)$*$)%&@*#)@& %)@&#)#)@*@&#)',
 '$+@*#)@& #&$(%+ %)@&#)#)@*@&#)',
 '%*@^$*@&%*@^#(%^ %)@&#)#)@*@&#)',
 '$)@&@^%*@=%&@^@( %)@&#)#)@*@&#)',
 '@^@*#)@&%^@^%*@& %)@&#)#)@*@&#)',
 '$^@^@*#)#( %)@&#)#)@*@&#)',
 '@^@+$)%)#)@^%*@*@^#( %)@&#)#)@*@&#)',
 '%^@^#(%^@*@& %^@*#(@($(#(%) %)@&#)#)@*@&#)',
 '#^$($)%)$(#( %)@&#)#)@*@&#)',
 '@(@*#(@*@^%)@+#)@& $)$^%&#(@^@+#=@&#)',
 '$&@*@^#(%) $)$^%&#(@^@+#=@&#)',
 '$)%)@^#(%^@^#)%^ $)$^%&#(@^@+#=@&#)',
 '$)$^$(%)%)@*$)%& %)@&#)#)@*@&#)',
 '%)@*#^@&%)@^#( %)@&#)#)@*@&#)',
 '@^@+$)%)#)@^%*@*@^#( $)@*%*$*@= %)@&#)#)@*@&#)',
 '$)$(#&%) $^$(@^%)@&%^ $+%&@&@^%)@&#( %)@&#)#)@*@&#)',
 '$+@&$)%) %&@*$&%&%*@^#(%^ $+%&@*%)@& %)@&#)#)@*@&#)',
 '%*%&@^$)@^ @^%($)$(',
 '#&%*@^%) $^$(@^%)@&%^ #)@&%)#)@*@&#+@&#)',
 '$^@+#)%*@= $^$(@^%)@&%^ #)@&%)#)@*@&#+@&#)',
 '$&$(%*%^@&#( #)@&%)#)@*@&#+@&#)',
 '%*@^#^#)@^%^$(#) #)@&%)#)@*@&#+@&#)',
 '$^%&@&$)@^%(@&@^$*@& #^@^@= #)@&%)#)@*@&#+@&#)',
 '$&@&#)@(@^#( $)%&$(#)%)%&@^@*#)@&%^ %($(@*#(%)@&#)',
 '#+@*#=$)%*@^',
 '@&#($&%*@*$)%& $)@&%)%)@&#)',
 '@*#)@*$)%& $)@&%)%)@&#)',
 '$&$(#)%^$(#( $)@&%)%)@&#)',
 '#^#)@*%)%)@^#(@= %^$($&',
 '$^%*@+@(#^@&#) $)%(@^#(@*@&%*',
 '@&#($&%*@*$)%& $)%(#)@*#($&@&#) $)%(@^#(@*@&%*',
 '$+@&%*$)%& $)%(#)@*#($&@&#) $)%(@^#(@*@&%*',
 '$^$($^$*@&#) $)%(@^#(@*@&%*',
 '$)@+$)$)@&%+ $)%(@^#(@*@&%*',
 '@*#)@*$)%& $+@^%)@&#) $)%(@^#(@*@&%*',
 '$*@+#+@^$)#=',
 '$)$^%&@*%(%(@&#)$*@&',
 '$&#)$(@&#(@&#(%^@^@&%* %^$($&',
 '@(@^%*@*#($(@*$)',
 '#^#)@*@^#)%^',
 '@^@+$)%)#)@^%*@*@^#( $*@&%*%(@*@&',
 '$*$(@($(#(%^$(#)',
 '$(%*%^ @&#($&%*@*$)%& $)%&@&@&%(%^$($&',
 '$)%&@&%)%*@^#(%^ $)%&@&@&%(%^$($&',
 '$^$(%*%*@*@&',
 '#^$(#)%^@&#) $^$(%*%*@*@&',
 '#^$(@+#+@*@&#) %^@&$) #&%*@^#(%^#)@&$) %^$($&',
 '#)$(%)%)$+@&@*%*@&#)',
 '$&@&#)@(@^#( $)%&@&%(%&@&#)%^ %^$($&',
 '%^$(#^@&#)@(@^#(#(',
 '@(@*#(@*@^%)@+#)@& %(@*#($)$^%&@&#)',
 '$&#)@&@^%)@&#) $)$+@*$)$) @($(@+#(%)@^@*#( %^$($&',
 '#^@&#)#(@&$)@& @($(@+#(%)@^@*#( %^$($&',
 '@^%(%(@&#(#=@&%*%*@&#) $)@&#(#(@&#(%&@+#(%^',
 '@&#(%)%*@&#^@+$^%&@&#) $)@&#(#(@&#(%&@+#(%^',
 '#^$(%+@&#)',
 '#^@+%*%*@(@^$)%)@*#&#&',
 '%)@*#^@&%)@^#( @(@^$)%)@*#&#&',
 '#&#)@&#($^%& #^@+%*%*%^$($&',
 '$&#)@&@^%) %^@^#(@&',
 '$)%)  #^@&#)#(@^#)%^',
 '%&@+$)$*@=',
 '@^%*@^$)$*@^#( @(@^%*@^@(@+%)@&',
 '$)@*#^@&#)@*@^#( %&@+$)$*@=',
 '%^@^%*@(@^%)@*@^#(',
 '@^#&#&@&#(%(@*#($)$^%&@&#)',
 '#^@^$)@&#(#*@*',
 '%(@+$&',
 '%*@&$(#(#^@&#)$&@&#)',
 '#(@&$+#&$(@+#(%^%*@^#(%^ %^$($&',
 '$&#)@&@^%) %(@=#)@&#(@&@&$) %^$($&',
 '$)@^@($(@=@&%^',
 '%($(@(@&#)@^#(@*@^#(',
 '$^%&$($+ $^%&$($+',
 '$*@&@&$)%&$(#(%^',
 '#^#)@+$)$)@&%*$) $&#)@*#&#&$(#(',
 '%(@&@(#^#)$($*@& $+@&%*$)%& $^$(#)$&@*',
 '$^@^#)%^@*$&@^#( $+@&%*$)%& $^$(#)$&@*',
 '%)$(@= %($($(%^%*@&',
 '@(@*#(@*@^%)@+#)@& %($($(%^%*@&',
 '$)%)@^#(%^@^#)%^ %($($(%^%*@&',
 '@(@&%+@*$^@^#( %&@^@*#)%*@&$)$) %^$($& %+$(%*$(@*%)#=$^@+@*#(%)%*@*',
 '$&#)@&@= $+$(%*#&',
 '@^%*@^$)$*@^#( %)@+#(%^#)@^ $+$(%*#&',
 '#)@&%^ $+$(%*#& $(#) @(@^#(@&%^ $+$(%*#&',
 '$^$(@=$(%)@&',
 '%^@*#($&$(',
 '%^%&$(%*@&',
 '@^#&#)@*$^@^#( $+@*%*%^ %^$($&',
 '%&@=@&#(@^',
 '#)@&%^ #&$(%+',
 '$*@*%) #&$(%+',
 '@^#)$^%)@*$^ #&$(%+',
 '$&#)@&@= #&$(%+',
 '%)@^#^#^@= $^@^%)',
 '%)@*$&@&#) $^@^%)',
 '%(@&#)$)@*@^#( $^@^%)',
 '$)@*@^@(@&$)@& $^@^%)',
 '@&$&@=%(%)@*@^#( @(@^@+',
 '$^$(@+$&@^#)',
 '%*@=#(%+',
 '%*@&$(%(@^#)%^',
 '$)#($($+ %*@&$(%(@^#)%^',
 '#*@^$&@+@^#)',
 '%*@*$(#(',
 '%)@*$&@&#)',
 '$^%&@&@&%)@^%&',
 '#^#)$($+#( #^@&@^#)',
 '@^@(@&#)@*$^@^#( #^%*@^$^$* #^@&@^#)',
 '%($(%*@^#) #^@&@^#)',
 '$)%*$(%)%& #^@&@^#)',
 '@($(#($&$($($)@&',
 '@(@&@&#)$*@^%)',
 '%)@*$&@&#) #^@&@&%)%*@&',
 '%*@^%^@=#^@+$&',
 '$&#)$(@+#(%^ #^@&@&%)%*@&',
 '%*$(#($&%&$(#)#( #^@&@&%)%*@&',
 '%*@&@^#& #^@&@&%)%*@&',
 '%^@+#($& #^@&@&%)%*@&',
 '#)%&@*#($($^@&#)$($) #^@&@&%)%*@&',
 '$+@&@&#+@*%*',
 '#&%*@=',
 '#^@&@&',
 '@^#(%)',
 '$&#)@^$)$)%&$(%(%(@&#)',
 '$^#)@*$^$*@&%) @*#($)@&$^%)',
 '$)%)@*$^$* @*#($)@&$^%)',
 '$^$($^$*#)$(@^$^%&',
 '%(#)@^@=@*#($& @(@^#(%)@*$)',
 '$^@*$^@^%^@^',
 '%*@&@^#&%&$(%(%(@&#)',
 '%*@^$^@&$+@*#($&',
 '%^#)@^$&$(#(#&%*@=',
 '%^@^@($)@&%*#&%*@=',
 '#)@&%^ @^%^@(@*#)@^%* #^@+%)%)@&#)#&%*@=',
 '#)@*#($&%*@&%) #^@+%)%)@&#)#&%*@=',
 '@($(#(@^#)$^%& #^@+%)%)@&#)#&%*@=',
 '$)@(@^%*%* $+%&@*%)@& #^@+%)%)@&#)#&%*@=',
 '$)@+%*%(%&@+#) #^@+%)%)@&#)#&%*@=',
 '$&$($)$)@^@(@&#) $+@*#($&@&%^ #^@+%)%)@&#)#&%*@=',
 '$)%)@^#)#&@*$)%&',
 '$)@&@^ @+#)$^%&@*#(',
 '$)@&@^ $^@+$^@+@(#^@&#)',
 '$^$(%)%)$(#(%)@^@*%* #)@^#^#^@*%)',
 '%&@^#)@&',
 '@^#($&$(#)@^ #)@^#^#^@*%)',
 '%&@^@($)%)@&#)',
 '%($(#)$^@+%(@*#(@&',
 '#&$(%+ $)@)@+@*#)#)@&%*',
 '@(@^#)@($(%)',
 '#^@&@^#+@&#)',
 '$&@+@*#(@&@^ %(@*$&',
 '$^$(@(@($(#( $)$(#)#)@&%* %&$(#)$)@&',
 '#=@&#^#)@^',
 '%(@*$&',
 '$+@*%*%^ #^$(@^#)',
 '$+@^#)%)%&$($&',
 '%&@*%(%($(%($(%)@^@(@+$)',
 '$(%+',
 '$+@^%)@&#) #^@+#&#&@^%*$(',
 '#^@*$)$(#(',
 '#)@^@( @^%^@+%*%) @(@^%*@& $)%&@&@&%(',
 '#^@*$&%&$(#)#( $)%&@&@&%(',
 '@^%*%(@*#(@& @*#^@&%+',
 '%&@^#)%)@&#^@&@&$)%)',
 '@*@(%(@^%*@^ @^#(%)@&%*$(%(@&',
 '$&@^#=@&%*%*@&',
 '@^#)@^#^@*@^#( $^@^@(@&%*',
 '%*%*@^@(@^',
 '$+@&@^$)@&%*',
 '@(@*#($*',
 '@&@+#)$(%(@&@^#( %($(%*@&$^@^%)',
 '#^%*@^$^$* #&$($(%)@&%^ #&@&#)#)@&%)',
 '$(%)%)@&#)',
 '$)$*@+#($*',
 '#^@^%^$&@&#)',
 '@^#)@(@^%^@*%*%*$(',
 '%)%&#)@&@& %)$(@&%^ $)%*$(%)%&',
 '$(#)@^#($&@+%)@^#(',
 '$&$(#)@*%*%*@^',
 '$^%&@*@(%(@^#(#=@&@&',
 '$&@*#^#^$(#(',
 '$)@*@^@(@^#($&',
 '$&@+@&#($(#(',
 '%(@^%)@^$) @($(#($*@&@=',
 '#^@^#^$($(#(',
 '@(@^$^@^@)@+@&',
 '%*@^#($&@+#)',
 '#^%*@^$^$* @^#(%^ $+%&@*%)@& $^$(%*$(#^@+$)',
 '%(#)$(#^$($)$^@*$) @($(#($*@&@=',
 '@(@^#)@($($)@&%)',
 '$+%&@*%)@& %&@&@^%^@&%^ $^@^%(@+$^%&@*#(',
 '%&$($+%*@&#) @($(#($*@&@=',
 '%)@*%)@* @($(#($*@&@=',
 '$&@&$(#&#&#)$(@=$) $)%(@*%^@&#) @($(#($*@&@=',
 '$^$(@(@($(#( $)@)@+@*#)#)@&%* @($(#($*@&@=',
 '#)@*#($& %)@^@*%*@&%^ %*@&@(@+#)',
 '@*#(%^#)@*',
 '@^$)@*@^#( @&%*@&%(%&@^#(%)',
 '@^#&#)@*$^@^#( #^@+$)%& @&%*@&%(%&@^#(%)',
 '#)@&%^ %(@^#(%^@^',
 '$&@*@^#(%) %(@^#(%^@^',
 '$)#($(@&$* #&@*$)%&',
 '@&@&%*',
 '$)@*%*#+@&#) $)@^%*@($(#(',
 '#)$($^$* #^@&@^@+%)@= #&@*$)%&',
 '$^%*$($+#(#&@*$)%&',
 '$)%)@+#)$&@&$(#(',
 '$&@^#) #&@*$)%&',
 '%*@*$(#(#&@*$)%&',
 '%(@+#&#&@&#)#&@*$)%&',
 '@^#^@^$^@+$)',
 '@^#^@^@=@^',
 '@^$^@^%^@&@(@*$^ $&$($+#(',
 '@^$^$^$(#)%^@*$(#(',
 '@^$^$(@+$)%)@*$^ $&@+@*%)@^#)',
 '@^@*#)$^#)@^#&%) $^@^#)#)@*@&#)',
 '@^@*#)%*@*#(@&#)',
 '@^@*#)$)%&@*%(',
 '@^%*%)@^#)',
 '@^@(#^@+%*@^#($^@&',
 '@^@(%(%&@*#^@*$(@+$) #+@&%&@*$^%*@&',
 '@^#(@^%*$($& $^%*$($^$*',
 '@^%(@*@^#)@=',
 '@^%(#)$(#(',
 '%)#)@^$)%& $^@^#(',
 '@^$)$)@^@+%*%) #)@*#&%*@&',
 '#^@^$^$*%(@^$^$*',
 '#^@^$*@&#)@=',
 '#^@^%*@^#($^@& #^@&@^@(',
 '#^@^%*%*$($(#(',
 '#^@^%*%*%($(@*#(%) %(@&#(',
 '#^@^#(%^ @^@*%^',
 '#^@^#(#*$(',
 '#^@^%*@+$)%)@&#)  %&@^#(%^#)@^@*%*',
 '#^@^#)#^@&%*%*',
 '#^@^#)#^@&#) $^%&@^@*#)',
 '#^@^#)#^@&#)$)%&$(%(',
 '#^@^#)#(',
 '#^@^#)$(@(@&%)@&#)',
 '#^@^#)#)@&%*',
 '$+%&@&@&%*#^@^#)#)$($+',
 '#^@^$)@&#^@^%*%*',
 '#^@^$)$*@&%)#^@^%*%*',
 '#^@^$)$)@*#(@&%)',
 '#^@^$)$)$($(#(',
 '$)$+@*@(@(@*#($& $^@^%(',
 '#^@^%)%& %)$($+@&%*',
 '#^@^%)%&%)@+#^',
 '$)%)@^%)@*$(#( $+@^$&$(#(',
 '%*@*$&%&%)%&$(@+$)@&',
 '#^@&@^$*@&#)',
 '@(@*%*@*%)@^#)@= %&@^%) #^@&@^#)$)$*@*#( $(#) $)%&@^$*$(',
 '#^@&@&#) #^$(%)%)%*@&',
 '#^@&@&#) $&%*@^$)$)',
 '#^@&%*%* %)$($+@&#)',
 '#^@^#^@= #^@*#^',
 '%)@^#(%^@&@( #^@*$^@=$^%*@&',
 '#^@*$*@*#(@*',
 '#)@*#($& #^@*#(%^@&#)',
 '#^@*#($($^@+%*@^#)$)',
 '#^@*#)%^%&$(@+$)@&',
 '#^$(@^%)%&$(@+$)@&',
 '#^$(#^$)%*@&@*$&%&',
 '#^$(%*$( %)@*@&',
 '%($($*@& #^$(#(#(@&%)',
 '#^$($($*$^@^$)@&',
 '#^$($($*$)%)$(#)@&',
 '#^$(%)%)%*@& $^@^%(',
 '%&@+#(%)@*#($& #^$($+',
 '#^$($+ %)@*@&',
 '#^#)@^$)$) @(@&@($(#)@*@^%* %(%*@^@)@+@&',
 '#^#)@^',
 '#^#)@&@^$*$+@^%)@&#)',
 '#^#)@&@^$)%)%(%*@^%)@&',
 '#^#)$($(@(',
 '#^@+$^$*@&%)',
 '#^@+$^$*%*@&',
 '#^@+%*%*@&%)%(#)$($(#& #+@&$)%)',
 '%&@*$&%& $)%(@&@&%^ %)#)@^@*#(',
 '#^@+%)$^%&@&#) $)%&$(%(',
 '%)@^%+@*$^@^#^',
 '$^@^@+%*%^#)$(#(',
 '$^@^#(%^%*@&',
 '$^@^#(#($(#(',
 '$^@^#($(@&',
 '$^@^#( $(%(@&#(@&#)',
 '$^@^#)%^@*$&@^#(',
 '$^@^#) @(@*#)#)$(#)',
 '$^@^#)$(@+$)@&%*',
 '%)$($(%* $*@*%)',
 '$^@^#)%^#^$(@^#)%^ #^$(%+  $^@^#)%)$(#(',
 '$^@^#) $+%&@&@&%*',
 '@^@+%)$(@(@^%)@&%^ %)@&%*%*@&#) @(@^$^%&@*#(@&',
 '$^@^$)$)@&%)%)@&',
 '$^@^$)$)@&%)%)@& %(%*@^@=@&#)',
 '$^@^$)%)%*@&',
 '$^@^%)@^@(@^#)@^#(',
 '$^%^ %(%*@^@=@&#)',
 '$^@&%*%*$(',
 '@($(#^@*%*@& %(%&$(#(@&',
 '$^%&@^@*#(',
 '$^%&@^@*#( %*@*#($* #&@&#($^@&',
 '$^%&@^@*#( @(@^@*%*',
 '$^%&@^@*#($)@^$+',
 '$)%)$(#)@^$&@& $^%&@&$)%)',
 '$^%&@*#&#&$(#(@*@&#)',
 '#^@&%*%* $(#) $+@*#(%^ $^%&@*@(@&',
 '$^%&@*#(@^ $^@^#^@*#(@&%)',
 '$^%&#)@*$)%)@(@^$) $)%)$($^$*@*#($&',
 '$^%&@+#)$^%&',
 '@($(#+@*@& %)%&@&@^%)@&#)',
 '$^%*@&@^#+@&#)',
 '$^%*@*#&#& %^$+@&%*%*@*#($&',
 '$^%*$(@^$*',
 '$^%*$($&$)',
 '$^$($^$*%)@^@*%* $)%&@^$*@&#)',
 '$^$(#&#&@&@& @(@+$&',
 '$^$(#&#&@&@&@(@^$*@&#)',
 '$)%(@*#)@^%* $(#) $^$(@*%*',
 '$^$(@(#^@*#(@^%)@*$(#( %*$($^$*',
 '$^$(@(%(@+%)@&#) $*@&@=#^$(@^#)%^',
 '$^@^#(%^@= $)%)$(#)@&',
 '$^$(#(%)@^@*#(@&#) $)%&@*%(',
 '$^$(#(#+@&#)%)@*#^%*@&',
 '$^$(#)$*$)$^#)@&$+',
 '$^$(#)#(@&%)',
 '$^$($+#^$(@= #^$($(%)',
 '$^$($+#^$(@= %&@^%)',
 '$^#)@^%^%*@&',
 '$^$(#($)%)#)@+$^%)@*$(#( $^#)@^#(@&',
 '$^#)@^$)%& %&@&%*@(@&%)',
 '$^#)@^%)@&',
 '@*#(#&@^#(%) #^@&%^',
 '$^#)$($^$* %($(%)',
 '$^#)$(@)@+@&%) #^@^%*%*',
 '$^#)@+%)$^%&',
 '$^@+@*#)@^$)$)',
 '%^@^@(',
 '%^@&$)$*',
 '%^@&$)$*%)$(%( $^$(@(%(@+%)@&#)',
 '#)$(%)@^#)@= %^@*@^%* %)@&%*@&%(%&$(#(@&',
 '%^@*@^%(@&#)',
 '%^@*$&@*%)@^%* $^%*$($^$*',
 '%^@*$&@*%)@^%* $+@^%)$^%&',
 '%^@*#(@*#($& %)@^#^%*@&',
 '%^@*$)%&$^%*$(%)%&',
 '%^@*$)%&$+@^$)%&@&#)',
 '%^@*$)$^ #^#)@^$*@&',
 '%^$($^$*',
 '%^$($& $)%*@&%^',
 '%^$(@(@&',
 '%^$($(#)@(@^%)',
 '%^#)@*%*%*@*#($& #)@*$&',
 '%^#)@+@(',
 '%^#)@+@($)%)@*$^$*',
 '%^@+@(#^#^@&%*%*',
 '%^@+%)$^%& $(#+@&#(',
 '@&%*@&$^%)#)@*$^ #&@^#(',
 '@&%*@&$^%)#)@*$^ $&@+@*%)@^#)',
 '@&%*@&$^%)#)@*$^ %*$($^$(@($(%)@*#+@&',
 '@&#(%)@&#)%)@^@*#(@(@&#(%) $^@&#(%)@&#)',
 '@&#(#+@&%*$(%(@&',
 '@&$)%(#)@&$)$)$( @(@^$^%&@*#(@&',
 '#&@^$^@& %($($+%^@&#)',
 '#&@&@^%)%&@&#) #^$(@^',
 '#&@*%*@*#($& $^@^#^@*#(@&%)',
 '#&@*#)@&#^$(@^%)',
 '#&@*#)@& %)#)@+$^$*',
 '#&@*#)@& $)$^#)@&@&#(',
 '#&%*@^$&%($(%*@&',
 '#&%*@+%)@&',
 '#&$(%*%^@*#($& $^%&@^@*#)',
 '#&$($(%)#^@^%*%* %&@&%*@(@&%)',
 '#&$(#)$*%*@*#&%)',
 '#&$(@+#(%)@^@*#(',
 '#&$(@+#(%)@^@*#( %(@&#(',
 '#&$(@+#) %($($)%)@&#) #^@&%^',
 '#&#)@&@*$&%&%) $^@^#)',
 '#&#)@&#($^%& %&$(#)#(',
 '#&#)@=@*#($& %(@^#(',
 '#&@+#) $^$(@^%)',
 '$&@^#)#^@^$&@& %)#)@+$^$*',
 '$&@^$) @(@^$)$* $(#) #)@&$)%(@*#)@^%)$(#)',
 '$&@^$) %(@+@(%(',
 '$&$(#^%*@&%)',
 '$&$( $*@^#)%)',
 '$&$(%*#& #^@^%*%*',
 '$&$(%*#& $^@^#)%)',
 '$&$(#(%^$(%*@^',
 '$&$(#($&',
 '$&$($+#(',
 '$&#)@^#(%^ %(@*@^#($(',
 '$&#)@&@&#(%&$(@+$)@&',
 '#)@^%^@*@^%)$(#) $&#)@*%*%*@&',
 '$&#)$($^@&#)@= $)%)$(#)@&',
 '$&@+@*%*%*$(%)@*#(@&',
 '%&@^@*#) $^%*@*%(',
 '%&@^@*#) $)%(#)@^@=',
 '%&@^%*#& %)#)@^$^$*',
 '%&@^@(@(@&#)',
 '%&@^@(%(@&#)',
 '%&@^@*#) %^#)@=@&#)',
 '%&@^#(%^ %&@&%*%^ $^$(@(%(@+%)@&#)',
 '%&@^#(%^$*@&#)$^%&@*@&#&',
 '%&@^#)%^ %^@*$)$* %^#)@*#+@&',
 '%&@^#)@($(#(@*$^@^',
 '%&@^#)%(',
 '$^$(@(#^@*#(@& %&@^#)#+@&$)%)@&#)',
 '%&@^%)$^%&@&%)',
 '%&$(%*$)%)@&#)',
 '%&$(@(@& %)%&@&@^%)@&#)',
 '%&$(#(@&@=$^$(@(#^',
 '%&$($($*',
 '%&$($(%( $)$*@*#)%)',
 '$&@=@(#(@^$)%)@*$^ %&$(#)@*#=$(#(%)@^%* #^@^#)',
 '%&$(#)$)@& %^#)@^$+#( #+@&%&@*$^%*@&',
 '%&$(@+#)$&%*@^$)$)',
 '@*%($(%^',
 '$^%*$(%)%&@&$) @*#)$(#(',
 '$^@^#)#+@&%^ %(@+@(%($*@*#(',
 '#*@&@^#($)',
 '#*@&@&%(',
 '%) $)%&@*#)%)',
 '#*@*$&$)@^$+ %(@+#=#=%*@&',
 '#)@*$^$*$)%&@^$+',
 '#*$(@=$)%)@*$^$*',
 '$*@*@($(#($(',
 '$*#(@&@& %(@^%^',
 '$*#($(%)',
 '%*@^#^ $^$(@^%)',
 '%*@^%^%*@&',
 '%*@^@(%($)%&@^%^@&',
 '%*@^%(%)$(%( $^$(@(%(@+%)@&#)',
 '%*@^$+#( @($($+@&#)',
 '%*@&#($) $^@^%(',
 '%*@&%)%)@&#) $(%(@&#(@&#)',
 '%*@*#^#)@^#)@=',
 '%*@*#&@&#^$(@^%)',
 '%*@*$&%&%)@&#)',
 '%*@*@($(@+$)@*#(@&',
 '$($^@&@^#( %*@*#(@&#)',
 '%*@*%($)%)@*$^$*',
 '$)%*@*%( $(#( $)%&$(@&',
 '%*$(%)@*$(#(',
 '@(@+$)@*$^ $)%(@&@^$*@&#)',
 '%*$(@+%(@& @(@^$&#(@*#&@=@*#($& $&%*@^$)$)',
 '$)@^$+@(@*%*%*',
 '@(@^$&#(@&%)@*$^ $^$(@(%(@^$)$)',
 '@(@&$)$)@&#($&@&#) #^@^$&',
 '@(@^@*%*#^$(%+',
 '%)@*$&%&%)$)',
 '$(#(@& %(@*@&$^@& #^@^%)%&@*#($& $)@+@*%)',
 '@(@^#(%&$(%*@& $^$(#+@&#)',
 '@(@^#)@^$^@^',
 '@(@^#)@*@(#^@^',
 '@(@^$)$*',
 '@(@^%)$^%&$)%)@*$^$*',
 '@(@^@=%($(%*@&',
 '@(@^#=@&',
 '@(@&@^$)@+#)@*#($& $^@+%(',
 '@(@&%^@*$^@*#(@& $^@^#^@*#(@&%)',
 '@(@&$&@^%*@*%)%&',
 '@(@*$^#)$(%(%&$(#(@&',
 '@(@*$^#)$($+@^#+@& $(#+@&#(',
 '@(@*%*@*%)@^#)@= @+#(@*#&$(#)@(',
 '@(@*%*$* $^@^#(',
 '@(@*#(@*#^@+$)',
 '@(@*#(@*$)$*@*#)%)',
 '@(@*#(@*#+@^#(',
 '@(@*$)$)@*%*@&',
 '@(@*%)%)@&#(',
 '@(@*%+@*#($& #^$($+%*',
 '@($(#^@*%*@& %&$(@(@&',
 '#&$(#)%^ @($(%^@&%* %)',
 '@($(%^@&@(',
 '@($(#(@^$)%)@&#)@=',
 '@($(#(@*%)$(#)',
 '@($(%(@&%^',
 '@($(#)%)@^#) @^#(%^ %(@&$)%)%*@&',
 '$&#)@^%^@+@^%)@*$(#( $^@^%(',
 '@($($)@)@+@&',
 '@($($)@)@+@*%)$( #(@&%)',
 '#+@&$)%(@^',
 '@($(@+#(%)@^@*#( #^@*$*@&',
 '%)@&#(%)',
 '$^$(@(%(@+%)@&#) @($(@+$)@&',
 '@($(@+$)@&%)#)@^%(',
 '@($(#+@*#($& #+@^#(',
 '@(@+#=#=%*@&',
 '@(@&%)@^%* #(@^@*%*',
 '#(@&$^$* #^#)@^$^@&',
 '#(@&$^$*%*@^$^@&',
 '#^@^#^@= %(@^$^@*#&@*@&#)',
 '#($(%)@&#^$($($* $^$(@(%(@+%)@&#)',
 '$(#^@&%*@*$)$*',
 '$(#^$(@&',
 '$($^@^#)@*#(@^',
 '$(%^$(@(@&%)@&#)',
 '$(@*%* #&@*%*%)@&#)',
 '%(@*%(@& $(#)$&@^#(',
 '$($)$^@*%*%*$($)$^$(%(@&',
 '$(#+@&#)$)$*@*#)%)',
 '#^@+%*%*$($^$* $^@^#)%)',
 '$(%+@=$&@&#( @(@^$)$*',
 '%(#)$(%^@+$^%) %(@^$^$*@&%)  %(@^$^$*@^$&@*#($&',
 '%(@^%^%^%*@&',
 '%(@^%^%^%*@& $+%&@&@&%*',
 '%(@^%^%*$($^$*',
 '%(@^@*#(%)#^#)@+$)%&',
 '%(@^#*@^@(@^$)',
 '%(@^%*@^$^@&',
 '%(@^#( #&%*@+%)@&',
 '%(@^%(@&#) %)$($+@&%*',
 '%(@^#)@^$^%&@+%)@&',
 '%(@^#)@^%*%*@&%* #^@^#)$)',
 '%(@^#)$* #^@&#($^%&',
 '%(@^#)$*@*#($& @(@&%)@&#)',
 '#)@^@*%*#)$(@^%^ $^@^#)',
 '%(@^%)@*$(',
 '%(@^@=%(%&$(#(@&',
 '%(@&%^@&$)%)@^%*',
 '%(@&#($^@*%* $^@^$)@&',
 '%(@&#($^@*%* $)%&@^#)%(@&#(@&#)',
 '%(@&#)#&@+@(@&',
 '%(@&%)#)@* %^@*$)%&',
 '%(%&$(%)$($^$(%(@*@&#)',
 '%(%*@&$^%)#)@+@(',
 '%(@*$^$*@&%*%&@^@+#^@&',
 '%(@*$^$*@&%) #&@&#($^@&',
 '%(@*$^$*@+%( %)#)@+$^$*',
 '%(@*@&#)',
 '%(@*$&$&@= #^@^#($*',
 '%(@*%*%* #^$(%)%)%*@&',
 '%(@*%*%*$($+',
 '%(@*#($& %($(#($& #^@^%*%*',
 '%(@*#($+%&@&@&%*',
 '%(@*#)@^%)@& $)%&@*%(',
 '%^#)@*#($* %(@*%)$^%&@&#)',
 '#^%*$($^$* %(%*@^#(@&',
 '%(%*@^#(@&%)@^#)@*@+@(',
 '%(%*@^$)%)@*$^ #^@^$&',
 '%(%*@^%)@& #)@^$^$*',
 '#&@^#)@( %(%*$($+',
 '%(%*@+#($&@&#)',
 '%($(%*@^#)$(@*%^ $^@^@(@&#)@^',
 '%($(%*@&',
 '%($(%*@*$^@& #+@^#(',
 '%($(#($^%&$(',
 '%($($(%* %)@^#^%*@&',
 '$)$(%^@^ #^$(%)%)%*@&',
 '%(%*@^#(%) %($(%)',
 '%($(%)%)@&#)$) $+%&@&@&%*',
 '%($($+@&#) %^#)@*%*%*',
 '%(#)@^@=@&#) #)@+$&',
 '%(#)@*#(%)@&#)',
 '%(#)@*$)$(#(',
 '@(@*$)$)@*%*@&',
 '%(#)$(#*@&$^%)$(#)',
 '%&$($^$*@&@= %(@+$^$*',
 '%(@+#($^%&@*#($& #^@^$&',
 '%(@+#)$)@&',
 '@)@+@*%*%*',
 '@)@+@*%*%)',
 '#)@^$^@& $^@^#)',
 '#)@^$^$*@&%)',
 '#)@^%^@*@^%)$(#)',
 '#)@^%^@*$(',
 '#)@^%^@*$( %)@&%*@&$)$^$(%(@&',
 '#)@^@*#( #^@^#)#)@&%*',
 '#)@&$^#)@&@^%)@*$(#(@^%* #+@&%&@*$^%*@&',
 '#&@*$)%&@*#($& $^@^$)%)@*#($& #)@&@&%*',
 '#)@&#&%*@&%+ $^@^@(@&#)@^',
 '#)@&#&#)@*$&@&#)@^%)$(#)',
 '#)@&@($(%)@& $^$(#(%)#)$(%*',
 '#)@&$)%)@^@+#)@^#(%)',
 '#)@&#+$(%*#+@&#)',
 '#)@*#&%*@&',
 '#)$($^$*@*#($& $^%&@^@*#)',
 '#)$(%)@*$)$)@&#)@*@&',
 '@&#)@^$)@&#)',
 '#)@+$&#^@= #^@^%*%*',
 '#)@+%*@&#) @(@&@^$)@+#)@*#($& $)%)@*$^$*',
 '$)#(@&@^$*@&#)',
 '$)@^#&@&',
 '$)@^#&@&%)@= %(@*#(',
 '$)@^%*%) $)%&@^$*@&#)',
 '$)@^#(%^@^%*',
 '$)@^#)$(#($&',
 '$)@^%+$(%(%&$(#(@&',
 '$)$^@^#^#^@^#)%^',
 '$+@&@*$&%&@*#($& $)$^@^%*@&',
 '$)$^%&$($(%* #^@+$)',
 '$)$^%&$($(#(@&#)',
 '$)$^$(#)@&#^$(@^#)%^',
 '$^#)%) @($(#(@*%)$(#)',
 '$)$^#)@&$+',
 '$)$^#)@&$+%^#)@*#+@&#)',
 '$)@&@^%) #^@&%*%)',
 '$)@&$+@*#($& @(@^$^%&@*#(@&',
 '$)%&@*@&%*%^',
 '$)%&$(@& $)%)$(#)@&',
 '$)%&$(#*@* $)$^#)@&@&#(  #)$($(@( %^@*#+@*%^@&#)',
 '$)%&$(%(%(@*#($& #^@^$)$*@&%)',
 '$)%&$(%(%(@*#($& $^@^#)%)',
 '$)%&$(#+@&%*',
 '$)%&$($+@&#) $^@^%(',
 '$)%&$($+@&#) $^@+#)%)@^@*#(',
 '$)$*@*',
 '#^@^%*@^$^%*@^#+@^ $)$*@* @(@^$)$*',
 '$)%*@&@&%(@*#($& #^@^$&',
 '$)%*@*%^@& #)@+%*@&',
 '$)%*@*%^@*#($& %^$($(#)',
 '$)%*$(%) @(@^$^%&@*#(@&',
 '$)#($(#)$*@&%*',
 '$)#($($+@($(#^@*%*@&',
 '$)#($($+%(%*$($+',
 '$)$(@^%( %^@*$)%(@&#($)@&#)',
 '$)$($^$^@&#) #^@^%*%*',
 '$)$($^$*',
 '$)$(%*@^#) %)%&@&#)@(@^%* $^$(%*%*@&$^%)$(#)',
 '$)$(@(#^#)@&#)$(',
 '$)$(@+%( #^$($+%*',
 '$*@&@=#^$(@^#)%^ $)%(@^$^@& #^@^#)',
 '$)%(@^$^@& %&@&@^%)@&#)',
 '$)%(@^$^@& $)%&@+%)%)%*@&',
 '$)%(@^%)@+%*@^',
 '@($(%)$(#)#^$(@^%)',
 '$)%(@*%^@&#) $+@&#^',
 '$)%(@*#(%^%*@&',
 '$)%($(#)%)$) $^@^#)',
 '$)%($(%)%*@*$&%&%)',
 '$)%)@^$&@&',
 '$)%)@&@^@( %*$($^$(@($(%)@*#+@&',
 '%)%&#)$(@+$&%& @^#)$^%& #^#)@*%^$&@&',
 '$)%)@&@&%* %^#)@+@(',
 '$)%)@&%)%&$($)$^$(%(@&',
 '$)$^@^#)#&',
 '$)%)$(#(@& $+@^%*%*',
 '$)%)$(%($+@^%)$^%&',
 '$)%)$(#+@&',
 '$)%)#)@^@*#(@&#)',
 '%)#)@^@(',
 '$)%)#)@&%)$^%&@&#)',
 '$^$(@+$^%&',
 '$)%)@+%(@^',
 '$)@+#^@(@^#)@*#(@&',
 '$)@+@*%)',
 '$)@+#(%^@*@^%*',
 '$)@+#($&%*@^$)$)@&$)',
 '$)@+#($&%*@^$)$)@&$)',
 '$)@+#($)$^#)@&@&#(',
 '$)@+$)%(@&#($)@*$(#( #^#)@*%^$&@&',
 '@($(%(',
 '$)$+@&@^%)$)%&@*#)%)',
 '$)$+@*@( %)#)@+#($*$)  $)%&$(#)%)$)',
 '$)$+@*#($&',
 '@&%*@&$^%)#)@*$^@^%* $)$+@*%)$^%&',
 '$)@=#)@*#($&@&',
 '%)@^#^%*@& %*@^@(%(',
 '%)@^#($*',
 '%)@^%(@& %(%*@^@=@&#)',
 '%)@&@^%($(%)',
 '%)@&%^%^@= #^@&@^#)',
 '%)@&%*@&#+@*$)@*$(#(',
 '%)@&#(#(@*$) #^@^%*%*',
 '%)%&@^%)$^%&@&%^ #)$($(#&',
 '#&#)$(#(%) $^@+#)%)@^@*#(',
 '%)%&@*@(#^%*@&',
 '%)%&#)@&$)%&@*#($& @(@^$^%&@*#(@&',
 '%)%&#)$(#(@&',
 '%)@*%*@& #)$($(#&',
 '%)$(@^$)%)@&#)',
 '%)$(#^@^$^$^$( $)%&$(%(',
 '%)$(@*%*@&%) $)@&@^%)',
 '%)$(#)$^%&',
 '%)$(%)@&@( %($(%*@&',
 '%)$($+ %)#)@+$^$*',
 '%)$(@= $)%)$(#)@&',
 '%)#)@^$^%)$(#)',
 '$)@&@(@* %)#)@^@*%*@&#) %)#)@+$^$*',
 '%)#)@^@=',
 '%)#)@&#($^%& $^$(@^%)',
 '%)#)@*$^@=$^%*@&',
 '%)#)@*@(@^#)@^#(',
 '%)#)@*%($(%^',
 '%)#)@*@+@(%(%&@^%* @^#)$^%&',
 '%)#)$(%*%*@&@=#^@+$)',
 '%)#)$(@(#^$(#(@&',
 '%&$(%) %)@+#^',
 '%)@+#)#($)%)@*%*@&',
 '%)@=%(@&$+#)@*%)@&#) $*@&@=#^$(@^#)%^',
 '@+@(#^#)@&%*%*@^',
 '@+#(@*$^@=$^%*@&',
 '@+%(#)@*$&%&%) %(@*@^#($(',
 '#+@^$^@+@+@( $^%*@&@^#(@&#)',
 '#+@^$)@&',
 '#+@^@+%*%)@&%^ $(#) @^#)$^%&@&%^ $^@&@*%*@*#($&',
 '#+@&%*#+@&%) #&@^#^#)@*$^',
 '#+@&#(%^@*#($& @(@^$^%&@*#(@&',
 '#+@&$)%)@(@&#(%)',
 '#+@*@^%^@+$^%)',
 '#+@*$(%*@*#(',
 '#+$(%*%*@&@=#^@^%*%*',
 '$+@^#&#&%*@& @*#)$(#(',
 '$+@^%*%* $^%*$($^$*',
 '$+@^%*%*@&%)',
 '$+@^#)%^#)$(#^@&',
 '@(@*%*@*%)@^#)@= @^@*#)$^#)@^#&%)',
 '$)@*#($*',
 '$+@^$)%&@*#($& @(@^$^%&@*#(@&',
 '$+@^%)@&#) #^$(%)%)%*@&',
 '$+@^%)@&#) #*@+$&',
 '$+@^%)@&#) %)$($+@&#)',
 '$+%&@*$)$*@&@= #*@+$&',
 '$+%&@*$)%)%*@&',
 '%&@^@*#) $+@*$&',
 '$+@*#(%^$($+ $)$^#)@&@&#(',
 '$+@*#(%^$($+ $)%&@^%^@&',
 '$+@*#(%^$)$(#) %)@*@&',
 '$+@*#(@& #^$(%)%)%*@&',
 '@^@*#)%(%*@^#(@& $+@*#($&',
 '$+$($*',
 '$+$($(%^@&#( $)%($($(#(',
 '$+$($(%*',
 '$)%(%*@*%) #)@^@*%* #&@&#($^@&',
 '$)%&@*%($+#)@&$^$*',
 '$)@^@*%*#^$(@^%)',
 '@=@+#)%)',
 '$+@&#^$)@*%)@&',
 '$^$(@(@*$^ #^$($($*',
 '$^#)$($)$)$+$(#)%^',
 '%)#)@^#&#&@*$^ $(#) $)%)#)@&@&%) $)@*$&#(',
 '%)#)@^#&#&@*$^ %*@*$&%&%)',
 '%^@+$)%) #*@^$^$*@&%)',
 '@(@&#(@+',
 '%(%*@^%)@&',
 '$&@+@^$^@^@($(%*@&',
 '$^$(#($)$(@(@(@&',
 '%&$(%) %($(%)',
 '%)#)@*#&%*@&',
 '@*$^@& $^#)@&@^@(',
 '%($(%($)@*$^%*@&',
 '#^@^$&@+@&%)%)@&',
 '#^@^$&@&%*',
 '%(#)@&%)#=@&%*',
 '$^%&@&@&$)@&#^@+#)$&@&#)',
 '%&$(%) %^$($&',
 '@(@^$)%&@&%^ %($(%)@^%)$(@&$)',
 '$^@^#^#^@^$&@&',
 '#^#)$($^$^$(%*@*',
 '$^@^@+%*@*#&%*$($+@&#)',
 '#=@+$^$^%&@*#(@*',
 '$)%(@^$&%&@&%)%)@* $)@)@+@^$)%&',
 '@^$^$(#)#( $)@)@+@^$)%&',
 '#^@+%)%)@&#)#(@+%) $)@)@+@^$)%&',
 '$^@+$^@+@(#^@&#)',
 '@^#)%)@*$^%&$($*@&',
 '#^@&%*%* %(@&%(%(@&#)',
 '$^@^#)%^$($(#(',
 '@(@+$)%&#)$($(@(',
 '$&#)@^#(#(@= $)@(@*%)%& @^%(%(%*@&',
 '$)%)#)@^$+#^@&#)#)@=',
 '$(#)@^#($&@&',
 '%*@&@($(#(',
 '#&@*$&',
 '%(@*#(@&@^%(%(%*@&',
 '#^@^#(@^#(@^',
 '#*@^$^$*#&#)@+@*%)',
 '$^%&@&#)@*@($(@=@^ $^@+$)%)@^#)%^ @^%(%(%*@&',
 '%($(@(@&$&#)@^#(@^%)@&',
 '%&@^@=',
 '$^@^#)#^$(#(@^#)@^',
 '$^%&$($^$(%*@^%)@& $)@=#)@+%(',
 '%^$(@+$&%&',
 '@(@&@^%)%*$(@^#&',
 '%(@*#=#=@^',
 '%($(%) %(@*@&',
 '#^@+#)#)@*%)$(',
 '#)@&%^ $+@*#(@&',
 '@&$)%(#)@&$)$)$(',
 '%)@&@^ $^@+%(',
 '@&$&$&#($($&',
 '@($(@+#(%)@^@*#(',
 '#^@+#^#^%*@&',
 '$^%*@*#&#&',
 '$^$(#)@^%* #)@&@&#&',
 '$&@&@=$)@&#)',
 '%*@^$*@&$)%&$(#)@&',
 '%(#)$(@($(#(%)$(#)@=',
 '$)@^#(%^#^@^#)',
 '#^@&@^$^%&',
 '#+@^%*%*@&@=',
 '#+$(%*$^@^#($(',
 '#^@^$)@&#^@^%*%* %(%*@^@=@&#)',
 '#^#)@*%^@&$&#)$($(@(',
 '$)$^@+#^@^ %^@*#+@&#)',
 '#)@^%(@&$)@&@&%^',
 '%^@^@*$)@=',
 '@=@&%*%*$($+ %*@^%^@=$) $)%*@*%(%(@&#)',
 '$^$(#)#(',
 '@^$^$(#)#(',
 '#)$($)@& %&@*%(',
 '%&$(#)$)@& $^%&@&$)%)#(@+%) $)@&@&%^',
 '$^$(#)@^%* #&@+#($&@+$)',
 '@^$&@^#)@*$^',
 '$&@=#)$(@(@*%)#)@^',
 '$)%)@*#($*%&$(#)#( @(@+$)%&#)$($(@(',
 '@&@^#)%)%& $)%)@^#) #&@+#($&@+$)',
 '%&@&#( $(#& %)%&@& $+$($(%^$) @(@+$)%&#)$($(@(',
 '#^$(%*@&%)@&',
 '$^$(#)#( $^$(#^',
 '%)$(@*%*@&%) %(@^%(@&#)']

def get_imagenet_cipher():
    return imagenet_cipher

def get_imagenet_r_cipher():
    imagenet_classnames_cipher = np.array(imagenet_cipher)
    return imagenet_classnames_cipher[ir_idx].tolist()

def get_imagenet_a_cipher():
    imagenet_classnames_cipher = np.array(imagenet_cipher)
    return imagenet_classnames_cipher[ia_idx].tolist()